In [1]:
import pandas as pd
import numpy as np
import re
from typing import NamedTuple

## Data

In [2]:
df_wine = pd.read_csv('wine-knowledge-discovery/data/WineDataset.csv')

In [3]:
df_wine.head()

,Title,Description,Price,Capacity,Grape,Secondary Grape Varieties,Closure,Country,Unit,Characteristics,Per bottle / case / each,Type,ABV,Region,Style,Vintage,Appellation
0,"The Guv'nor, Spain",We asked some of our most prized winemakers wo...,£9.99 per bottle,75CL,Tempranillo,NaN,Natural Cork,Spain,10.5,"Vanilla, Blackberry, Blackcurrant",per bottle,Red,ABV 14.00%,NaN,Rich & Juicy,NV,NaN
1,Bread & Butter 'Winemaker's Selection' Chardon...,This really does what it says on the tin. It’s...,£15.99 per bottle,75CL,Chardonnay,NaN,Natural Cork,USA,10.1,"Vanilla, Almond, Coconut, Green Apple, Peach, ...",per bottle,White,ABV 13.50%,California,Rich & Toasty,2021,Napa Valley
2,"Oyster Bay Sauvignon Blanc 2022, Marlborough",Oyster Bay has been an award-winning gold-stan...,£12.49 per bottle,75CL,Sauvignon Blanc,NaN,Screwcap,New Zealand,9.8,"Tropical Fruit, Gooseberry, Grapefruit, Grass,...",per bottle,White,ABV 13.00%,Marlborough,Crisp & Zesty,2022,NaN
3,Louis Latour Mâcon-Lugny 2021/22,We’ve sold this wine for thirty years – and fo...,£17.99 per bottle,75CL,Chardonnay,NaN,Natural Cork,France,10.1,"Peach, Apricot, Floral, Lemon",per bottle,White,ABV 13.50%,Burgundy,Ripe & Rounded,2022,Macon
4,Bread & Butter 'Winemaker's Selection' Pinot N...,Bread & Butter is that thing that you can coun...,£15.99 per bottle,75CL,Pinot Noir,NaN,Natural Cork,USA,10.1,"Smoke, Black Cherry, Cedar, Raspberry, Red Fruit",per bottle,Red,ABV 13.50%,California,Smooth & Mellow,2021,Napa Valley

### volumes Liters fix (standartisation)

In [4]:
df_wine.Capacity.value_counts()

Capacity
75CL      1193
37.5CL      23
750ML       18
1.5LTR      18
150CL       11
50CL         8
Our          6
2.25L        4
70CL         3
500ML        3
300CL        1
5LITRE       1
375ML        1
Name: count, dtype: int64

In [4]:
def convert_to_liters(value):
    if pd.isna(value):
        return np.nan
    
    value = str(value).upper().strip()
    
    # Extract numeric part
    number = re.findall(r"[\d.]+", value)
    if not number:
        return np.nan
    
    number = float(number[0])
    
    # Convert based on unit
    if "ML" in value:
        return number / 1000
    elif "CL" in value:
        return number / 100
    elif "L" in value:   # catches L, LTR, LITRE
        return number
    else:
        return np.nan

# Apply
df_wine["Capacity_L"] = df_wine["Capacity"].apply(convert_to_liters)

### Characteristics OHE

In [5]:
ohe = df_wine["Characteristics"].str.get_dummies(sep=", ")
ohe.head()

,Almond,Apricot,Asparagus,Banana,Biscuit,Black Cherry,Black Fruit,Black Pepper,Black Plum,Blackberry,...,Tobacco,Toffee,Tomato Leaf,Tropical Fruit,Vanilla,Violet,Walnut,Watermelon,Wet Stones,White Pepper
0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Style OHE

In [9]:
df_wine['Style'].unique()

array(['Rich & Juicy', 'Rich & Toasty', 'Crisp & Zesty', 'Ripe & Rounded',
       'Smooth & Mellow', nan, 'Light & Refreshing', 'Crisp & Fruity',
       'Fresh & Elegant ', 'Delicate & Dry', 'Bold & Spicy',
       'Savoury & Full Bodied', 'Soft & Fruity', 'Aromatic & Floral',
       'Smooth & Light', 'Ripe & Fruity', 'Light & Elegant'], dtype=object)

In [6]:
df_wine["Style"] = (
    df_wine["Style"]
    .str.strip()                 # remove trailing spaces
)

# Split on &
split_styles = (
    df_wine["Style"]
    .dropna()
    .str.split("&")
    .apply(lambda x: [i.strip() for i in x])
)

# One-hot encode
ohe2 = (
    split_styles
    .explode()
    .str.get_dummies()
    .groupby(level=0)
    .sum()
)

In [13]:
ohe2

,Aromatic,Bold,Crisp,Delicate,Dry,Elegant,Floral,Fresh,Fruity,Full Bodied,...,Refreshing,Rich,Ripe,Rounded,Savoury,Smooth,Soft,Spicy,Toasty,Zesty
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1285,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1286,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1287,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
1288,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
1289,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
%pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 4.3 MB/s eta 0:00:0000:0100:01
Collecting matplotlib>=3.10.8
  Using cached matplotlib-3.10.8-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
Collecting mlxtend
  Downloading mlxtend-0.23.4-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 1.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: scikit-learn>=1.3.1 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from mlxtend) (1.7.2)
Requirement already satisfied: joblib>=0.13.2 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: matplotlib>=3.0.0 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from mlxtend) (3.10.7)
Requirement already satisfied: pandas>=0.24.2 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scipy>=1.2.1 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from mlxtend) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from mlxtend) (2.2.6)
Requirement already satisfied: cycler>=0.10 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pillow>=8 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (12.0.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (4.60.1)
Requirement already satisfied: pyparsing>=3 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.5)
Requirement already satisfied: packaging>=20.0 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.9)
Requirement already satisfied: contourpy>=1.0.1 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: tzdata>=2022.7 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: pytz>=2020.1 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /home/tacit/NN_labs/.NNvenv/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.4
Note: you may need to restart the kernel to use updated packages.

In [11]:
ohe = ohe.add_prefix("ch_")
ohe2 = ohe2.add_prefix("st_")

In [12]:
ohe3 = df_wine["Style"].str.get_dummies()

In [16]:
df_wine.Grape.unique()

array(['Tempranillo', 'Chardonnay', 'Sauvignon Blanc', 'Pinot Noir',
       'Glera', nan, 'Chenin Blanc', 'Castelão ', 'Malagousia',
       'Cinsault', 'Grenache', 'Shiraz', 'Cabernet Sauvignon', 'Bacchus',
       'Viognier', 'Pinot Grigio', 'Garnacha', 'Malbec', 'Cortese',
       'Merlot', 'Melon De Bourgogne', 'Carménère', 'Zinfandel', 'Syrah',
       'Marsanne', 'Gruner Veltliner', 'Corvina', 'Greco', 'Macabeo',
       'Gamay', 'Loureiro', 'Riesling', 'Alvarinho', 'Mourvèdre',
       'Cabernet Franc', 'Vespaiola', 'Picpoul', 'Vermentino',
       'Sangiovese', 'Pinot Meunier', 'Verdejo', 'Primitivo', 'Pinotage',
       'Alicante Bouschet', 'Garganega', 'Godello', 'Carignan',
       'Grenache Blanc', 'Aligoté', 'Siegerrebe', 'Touriga Nacional',
       'Albarino', 'Nerello Mascalese', "Nero D'Avola", 'Turbiana',
       'Pinot Gris', 'Airen', 'Trincadeira', 'Tinta Roriz', 'Xinomavro',
       'Agiorgitiko', 'Pais', 'Gewürztraminer', 'Mencia', 'Verdicchio',
       'Fiano', 'Rondinella', 'Mauzac', 'Nebbiolo',
       'Lambrusco Grasparossa', 'Pecorino', 'Negroamaro', 'Fernão Pires',
       'Feteasca Alba', 'Zwieigelt', 'Grillo', 'Tinta Barroca', 'Furmint',
       'Touriga Franca', 'Pedro Ximénez', 'Palomino', 'Viura',
       'Montepulciano', 'Barbera', 'Malvasia', 'Arinto', 'Colombard',
       'Sémillon', 'Jacquere', 'Pinot Blanc', 'Rkatsiteli',
       'Syrah-Shiraz', 'Torrontes', 'Sauvignon Gris', 'Assyrtiko',
       'Moscato', 'Rolle', 'Huxelrebe', 'Xarel-Lo', 'Niellucciu',
       'Saperavi', 'Rara Neagra', 'Non Varietal', 'Muscat', 'Monastrell',
       'Dolcetto', 'Black Muscat', 'Nerello', 'Roussanne', 'Tibouren',
       'Grolleau', 'Inzolia', 'Falanghina', 'Aglianico'], dtype=object)

In [7]:
ohe_grape = df_wine["Grape"].str.get_dummies()

In [15]:
char_cols = list(ohe.columns)

In [34]:
styl_cols = list(ohe2.columns)
styl_cols2 = list(ohe3.columns)

In [35]:
ohe_cs = ohe.join(ohe3)

In [17]:
df_wine = df_wine.join(ohe)

In [18]:
df_wine = df_wine.join(ohe2)

In [17]:
context2 = ohe.join(ohe_grape)

In [ ]:
# fca_df = df_wine[char_cols + styl_cols].astype(bool)

fca_df = ohe_cs.astype(bool)
fca_df2 = context2.astype(bool)

In [38]:
fca_df.head()

,ch_Almond,ch_Apricot,ch_Asparagus,ch_Banana,ch_Biscuit,ch_Black Cherry,ch_Black Fruit,ch_Black Pepper,ch_Black Plum,ch_Blackberry,...,Light & Elegant,Light & Refreshing,Rich & Juicy,Rich & Toasty,Ripe & Fruity,Ripe & Rounded,Savoury & Full Bodied,Smooth & Light,Smooth & Mellow,Soft & Fruity
0,False,False,False,False,False,False,False,False,False,True,...,False,False,True,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [19]:
fca_df2.head()

,ch_Almond,ch_Apricot,ch_Asparagus,ch_Banana,ch_Biscuit,ch_Black Cherry,ch_Black Fruit,ch_Black Pepper,ch_Black Plum,ch_Blackberry,...,Verdejo,Verdicchio,Vermentino,Vespaiola,Viognier,Viura,Xarel-Lo,Xinomavro,Zinfandel,Zwieigelt
0,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [20]:
from mlxtend.frequent_patterns import apriori, association_rules

In [44]:


# freq = apriori(fca_df, min_support=0.005, use_colnames=True, low_memory=True)
freq2 = apriori(fca_df2, min_support=0.01, use_colnames=True, low_memory=True)

In [30]:
# rules = association_rules(freq, metric="confidence", min_threshold=0.6)
rules2 = association_rules(freq2, metric="confidence", min_threshold=0.6)

In [45]:
freq2

      support                                           itemsets
0    0.034109                                        (ch_Almond)
1    0.068992                                       (ch_Apricot)
2    0.031783                                       (ch_Biscuit)
3    0.096124                                  (ch_Black Cherry)
4    0.116279                                   (ch_Black Fruit)
..        ...                                                ...
744  0.010853  (ch_Raspberry, Grenache, ch_Peach, ch_Strawber...
745  0.010078  (ch_Black Plum, ch_Blackcurrant, ch_Tobacco, c...
746  0.011628  (ch_Black Plum, ch_Raspberry, Grenache, ch_Spi...
747  0.011628  (ch_Lemon, ch_Peach, ch_Green Apple, ch_Vanill...
748  0.011628  (ch_Lemon, ch_Stone Fruit, ch_Tropical Fruit, ...

[749 rows x 2 columns]

In [93]:
freq

       support                                           itemsets
0     0.034109                                        (ch_Almond)
1     0.068992                                       (ch_Apricot)
2     0.031783                                       (ch_Biscuit)
3     0.096124                                  (ch_Black Cherry)
4     0.116279                                   (ch_Black Fruit)
...        ...                                                ...
1888  0.006202  (ch_Blueberry, ch_Black Plum, ch_Tobacco, ch_C...
1889  0.006202  (ch_Blackcurrant, ch_Blueberry, ch_Black Plum,...
1890  0.006202  (ch_Blackcurrant, ch_Blueberry, ch_Tobacco, ch...
1891  0.006202  (ch_Stone Fruit, ch_Butter, ch_Hazelnut, ch_Br...
1892  0.006202  (ch_Blackcurrant, ch_Blueberry, ch_Black Plum,...

[1893 rows x 2 columns]

In [94]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(ch_Apricot),(ch_Peach),0.068992,0.189922,0.055039,0.797753,4.200413,1.0,0.041936,4.005383,0.818391,0.269962,0.750336,0.543774
1,(ch_Biscuit),(ch_Bread),0.031783,0.065116,0.024806,0.780488,11.986063,1.0,0.022737,4.258915,0.946657,0.344086,0.765198,0.580720
2,(ch_Biscuit),(ch_Citrus Fruit),0.031783,0.185271,0.023256,0.731707,3.949383,1.0,0.017367,3.036716,0.771310,0.120000,0.670697,0.428615
3,(ch_Biscuit),(Rich & Toasty),0.031783,0.109302,0.022481,0.707317,6.471199,1.0,0.019007,3.043217,0.873223,0.189542,0.671400,0.456495
4,(ch_Ripe Fruit),(ch_Black Fruit),0.029457,0.116279,0.024806,0.842105,7.242105,1.0,0.021381,5.596899,0.888079,0.205128,0.821330,0.527719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6150,"(Bold & Spicy, ch_Chocolate, ch_Tobacco)","(ch_Blackcurrant, ch_Blueberry, ch_Black Plum,...",0.006977,0.008527,0.006202,0.888889,104.242424,1.0,0.006142,8.923256,0.997365,0.666667,0.887933,0.808081
6151,"(ch_Blackberry, Bold & Spicy, ch_Tobacco)","(ch_Blackcurrant, ch_Blueberry, ch_Black Plum,...",0.007752,0.009302,0.006202,0.800000,86.000000,1.0,0.006129,4.953488,0.996094,0.571429,0.798122,0.733333
6152,"(Bold & Spicy, ch_Vanilla, ch_Tobacco)","(ch_Blackcurrant, ch_Blueberry, ch_Black Plum,...",0.007752,0.010853,0.006202,0.800000,73.714286,1.0,0.006117,4.945736,0.994141,0.500000,0.797806,0.685714
6153,"(ch_Blueberry, ch_Tobacco)","(ch_Blackcurrant, ch_Black Plum, ch_Chocolate,...",0.010078,0.010078,0.006202,0.615385,61.065089,1.0,0.006100,2.573798,0.993637,0.444444,0.611469,0.615385
6154,"(Bold & Spicy, ch_Tobacco)","(ch_Blackcurrant, ch_Blueberry, ch_Black Plum,...",0.008527,0.008527,0.006202,0.727273,85.289256,1.0,0.006129,3.635401,0.996775,0.571429,0.724927,0.727273

In [95]:
rules_df = rules[
    rules['antecedents'].apply(lambda x: any(i in styl_cols2 for i in x)) &
    rules['consequents'].apply(lambda x: any(i in char_cols for i in x))
]

In [46]:
rules_df2 = rules2[
    rules2['antecedents'].apply(lambda x: any(i in ohe_grape.columns for i in x)) &
    rules2['consequents'].apply(lambda x: any(i in ohe.columns for i in x))
]

In [47]:
rules_df.head(50)

NameError: name 'rules_df' is not defined

In [48]:
rules_df2.head(50)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1,(Viognier),(ch_Apricot),0.016279,0.068992,0.013178,0.809524,11.733547,1.0,0.012055,4.887791,0.929912,0.182796,0.795409,0.500268
6,(Malbec),(ch_Black Fruit),0.028682,0.116279,0.022481,0.783784,6.740541,1.0,0.019145,4.087209,0.876792,0.183544,0.755334,0.488559
11,(Shiraz),(ch_Black Plum),0.033333,0.127907,0.023256,0.697674,5.454545,1.0,0.018992,2.884615,0.844828,0.168539,0.653333,0.439746
14,(Shiraz),(ch_Blackberry),0.033333,0.124031,0.024806,0.744186,6.000000,1.0,0.020672,3.424242,0.862069,0.187135,0.707965,0.472093
15,(Syrah),(ch_Blackberry),0.013953,0.124031,0.009302,0.666667,5.375000,1.0,0.007572,2.627907,0.825472,0.072289,0.619469,0.370833
18,(Cabernet Sauvignon),(ch_Blackcurrant),0.067442,0.111628,0.047287,0.701149,6.281130,1.0,0.039758,2.972630,0.901598,0.358824,0.663598,0.562380
23,(Glera),(ch_Citrus Fruit),0.013953,0.185271,0.009302,0.666667,3.598326,1.0,0.006717,2.444186,0.732311,0.048980,0.590866,0.358438
29,(Sauvignon Blanc),(ch_Grass),0.079070,0.060465,0.054264,0.686275,11.349925,1.0,0.049483,2.994767,0.990188,0.636364,0.666084,0.791855
31,(Sauvignon Blanc),(ch_Green Apple),0.079070,0.189147,0.058140,0.735294,3.887416,1.0,0.043184,3.063221,0.806532,0.276753,0.673546,0.521336
34,(Viognier),(ch_Peach),0.016279,0.189922,0.013178,0.809524,4.262391,1.0,0.010087,4.252907,0.778056,0.068273,0.764867,0.439456
37,(Gamay),(ch_Raspberry),0.016279,0.147287,0.010853,0.666667,4.526316,1.0,0.008455,2.558140,0.791962,0.071066,0.609091,0.370175
38,(Grenache),(ch_Raspberry),0.063566,0.147287,0.040310,0.634146,4.305520,1.0,0.030948,2.330749,0.819855,0.236364,0.570953,0.453915
41,(Malbec),(ch_Red Fruit),0.028682,0.158915,0.021705,0.756757,4.762030,1.0,0.017147,3.457795,0.813334,0.130841,0.710798,0.446671
43,(Malbec),(ch_Ripe Fruit),0.028682,0.029457,0.020930,0.729730,24.772404,1.0,0.020085,3.591008,0.987970,0.562500,0.721527,0.720128
45,(Shiraz),(ch_Vanilla),0.033333,0.200775,0.020930,0.627907,3.127413,1.0,0.014238,2.147917,0.703704,0.098182,0.534433,0.366077
46,(Tempranillo),(ch_Vanilla),0.043411,0.200775,0.029457,0.678571,3.379757,1.0,0.020742,2.486477,0.736074,0.137184,0.597825,0.412645
47,(Malbec),(ch_Violet),0.028682,0.041085,0.020930,0.729730,17.761346,1.0,0.019752,3.547984,0.971565,0.428571,0.718150,0.619582
52,"(ch_Apricot, Chardonnay)",(ch_Lemon),0.025581,0.156589,0.018605,0.727273,4.644464,1.0,0.014599,3.092506,0.805290,0.113744,0.676638,0.423042
54,"(ch_Apricot, Chardonnay)",(ch_Peach),0.025581,0.189922,0.022481,0.878788,4.627087,1.0,0.017622,6.683140,0.804461,0.116466,0.850370,0.498578
55,"(Viognier, ch_Peach)",(ch_Apricot),0.013178,0.068992,0.011628,0.882353,12.789161,1.0,0.010719,7.913566,0.934119,0.164835,0.873635,0.525446
56,"(Viognier, ch_Apricot)",(ch_Peach),0.013178,0.189922,0.011628,0.882353,4.645858,1.0,0.009125,6.885659,0.795234,0.060729,0.854771,0.471789
57,(Viognier),"(ch_Peach, ch_Apricot)",0.016279,0.055039,0.011628,0.714286,12.977867,1.0,0.010732,3.307364,0.938219,0.194805,0.697644,0.462777
64,"(ch_Biscuit, Chardonnay)",(ch_Bread),0.026357,0.065116,0.022481,0.852941,13.098739,1.0,0.020764,6.357209,0.948660,0.325843,0.842698,0.599090
68,"(ch_Biscuit, Chardonnay)",(ch_Citrus Fruit),0.026357,0.185271,0.020930,0.794118,4.286242,1.0,0.016047,3.957254,0.787450,0.109756,0.747299,0.453544
71,"(Cabernet Sauvignon, ch_Black Cherry)",(ch_Black Plum),0.016279,0.127907,0.010078,0.619048,4.839827,1.0,0.007995,2.289244,0.806510,0.075145,0.563175,0.348918
74,"(ch_Blackberry, Pinot Noir)",(ch_Black Cherry),0.014729,0.096124,0.013178,0.894737,9.308149,1.0,0.011763,8.586822,0.905910,0.134921,0.883542,0.515917
76,"(Cabernet Sauvignon, ch_Black Cherry)",(ch_Blackcurrant),0.016279,0.111628,0.012403,0.761905,6.825397,1.0,0.010586,3.731163,0.867612,0.107383,0.731987,0.436508
81,"(ch_Black Cherry, Pinot Noir)",(ch_Red Fruit),0.024806,0.158915,0.017829,0.718750,4.522866,1.0,0.013887,2.990525,0.798714,0.107477,0.665611,0.415473
83,"(Pinot Noir, ch_Sweet Spice)",(ch_Black Cherry),0.017054,0.096124,0.013178,0.772727,8.038856,1.0,0.011539,3.977054,0.890796,0.131783,0.748558,0.454912
89,"(Cabernet Sauvignon, ch_Black Fruit)",(ch_Blackcurrant),0.016279,0.111628,0.010078,0.619048,5.545635,1.0,0.008260,2.331977,0.833242,0.085526,0.571179,0.354663
98,"(ch_Black Fruit, Malbec)",(ch_Red Fruit),0.022481,0.158915,0.021705,0.965517,6.075694,1.0,0.018133,24.391473,0.854622,0.135922,0.959002,0.551051
99,"(Malbec, ch_Red Fruit)",(ch_Black Fruit),0.021705,0.116279,0.021705,1.000000,8.600000,1.0,0.019182,inf,0.903328,0.186667,1.000000,0.593333
100,(Malbec),"(ch_Black Fruit, ch_Red Fruit)",0.028682,0.067442,0.021705,0.756757,11.220876,1.0,0.019771,3.833850,0.937778,0.291667,0.739166,0.539298
101,"(ch_Black Fruit, Tempranillo)",(ch_Red Fruit),0.025581,0.158915,0.025581,1.000000,6.292683,1.0,0.021516,inf,0.863166,0.160976,1.000000,0.580488
102,"(ch_Red Fruit, Tempranillo)",(ch_Black Fruit),0.025581,0.116279,0.025581,1.000000,8.600000,1.0,0.022607,inf,0.906921,0.220000,1.000000,0.610000
107,"(ch_Black Fruit, Malbec)",(ch_Ripe Fruit),0.022481,0.029457,0.020930,0.931034,31.606171,1.0,0.020268,14.072868,0.990631,0.675000,0.928941,0.820780
109,"(Malbec, ch_Ripe Fruit)",(ch_Black Fruit),0.020930,0.116279,0.020930,1.000000,8.600000,1.0,0.018496,inf,0.902613,0.180000,1.000000,0.590000
110,(Malbec),"(ch_Black Fruit, ch_Ripe Fruit)",0.028682,0.024806,0.020930,0.729730,29.417230,1.0,0.020219,3.608217,0.994532,0.642857,0.722855,0.786740
112,"(Cabernet Sauvignon, ch_Tobacco)",(ch_Black Fruit),0.015504,0.116279,0.009302,0.600000,5.160000,1.0,0.007500,2.209302,0.818898,0.075949,0.547368,0.340000
114,"(ch_Black Fruit, Tempranillo)",(ch_Vanilla),0.025581,0.200775,0.025581,1.000000,4.980695,1.0,0.020445,inf,0.820207,0.127413,1.000000,0.563707
115,"(Tempranillo, ch_Vanilla)",(ch_Black Fruit),0.029457,0.116279,0.025581,0.868421,7.468421,1.0,0.022156,6.716279,0.892390,0.212903,0.851108,0.544211
117,"(ch_Black Fruit, Malbec)",(ch_Violet),0.022481,0.041085,0.020930,0.931034,22.661028,1.0,0.020007,13.904264,0.977854,0.490909,0.928080,0.720234
118,"(ch_Violet, Malbec)",(ch_Black Fruit),0.020930,0.116279,0.020930,1.000000,8.600000,1.0,0.018496,inf,0.902613,0.180000,1.000000,0.590000
119,(Malbec),"(ch_Black Fruit, ch_Violet)",0.028682,0.023256,0.020930,0.729730,31.378378,1.0,0.020263,3.613953,0.996719,0.675000,0.723295,0.814865
121,"(Shiraz, ch_Black Pepper)",(ch_Black Plum),0.017829,0.127907,0.011628,0.652174,5.098814,1.0,0.009347,2.507267,0.818469,0.086705,0.601159,0.371542
126,"(Shiraz, ch_Black Pepper)",(ch_Blackberry),0.017829,0.124031,0.013953,0.782609,6.309783,1.0,0.011742,4.029457,0.856792,0.109091,0.751828,0.447554
146,"(Cabernet Sauvignon, ch_Blackberry)",(ch_Black Plum),0.024031,0.127907,0.014729,0.612903,4.791789,1.0,0.011655,2.252907,0.810794,0.107345,0.556129,0.364027
147,"(ch_Blackberry, Grenache)",(ch_Black Plum),0.018605,0.127907,0.013953,0.750000,5.863636,1.0,0.011574,3.488372,0.845182,0.105263,0.713333,0.429545
148,"(Grenache, ch_Black Plum)",(ch_Blackberry),0.017054,0.124031,0.013953,0.818182,6.596591,1.0,0.011838,4.817829,0.863127,0.109756,0.792438,0.465341
149,"(ch_Blackberry, Shiraz)",(ch_Black Plum),0.024806,0.127907,0.019380,0.781250,6.107955,1.0,0.016207,3.986711,0.857552,0.145349,0.749167,0.466383

In [49]:
rules_df2_2 = rules2[
    rules2['consequents'].apply(lambda x: any(i in ohe_grape.columns for i in x)) &
    rules2['antecedents'].apply(lambda x: any(i in ohe.columns for i in x))
    
]

In [51]:
rules_df2_2.head(50)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
4,(ch_Biscuit),(Chardonnay),0.031783,0.183721,0.026357,0.829268,4.513739,1.0,0.020517,4.781063,0.804008,0.139344,0.790841,0.486364
19,(ch_Bread),(Chardonnay),0.065116,0.183721,0.050388,0.773810,4.211875,1.0,0.038424,3.608813,0.815691,0.253906,0.722901,0.524036
22,(ch_Butter),(Chardonnay),0.034884,0.183721,0.031008,0.888889,4.838256,1.0,0.024599,7.346512,0.821988,0.165289,0.863881,0.528833
24,(ch_Cream),(Chardonnay),0.059690,0.183721,0.041085,0.688312,3.746507,1.0,0.030119,2.618895,0.779620,0.203065,0.618160,0.455970
26,(ch_Gooseberry),(Sauvignon Blanc),0.023256,0.079070,0.020930,0.900000,11.382353,1.0,0.019091,9.209302,0.933862,0.257143,0.891414,0.582353
30,(ch_Grass),(Sauvignon Blanc),0.060465,0.079070,0.054264,0.897436,11.349925,1.0,0.049483,8.979070,0.970580,0.636364,0.888630,0.791855
32,(ch_Hazelnut),(Chardonnay),0.027132,0.183721,0.020155,0.742857,4.043400,1.0,0.015170,3.174419,0.773675,0.105691,0.684982,0.426281
33,(ch_Pastry),(Chardonnay),0.013178,0.183721,0.009302,0.705882,3.842144,1.0,0.006881,2.775349,0.749607,0.049587,0.639685,0.378258
44,(ch_Ripe Fruit),(Malbec),0.029457,0.028682,0.020930,0.710526,24.772404,1.0,0.020085,3.355462,0.988759,0.562500,0.701978,0.720128
53,"(ch_Apricot, ch_Lemon)",(Chardonnay),0.026357,0.183721,0.018605,0.705882,3.842144,1.0,0.013762,2.775349,0.759753,0.097166,0.639685,0.403574
63,"(ch_Biscuit, ch_Bread)",(Chardonnay),0.024806,0.183721,0.022481,0.906250,4.932753,1.0,0.017923,8.706977,0.817554,0.120833,0.885150,0.514306
65,(ch_Biscuit),"(ch_Bread, Chardonnay)",0.031783,0.050388,0.022481,0.707317,14.037523,1.0,0.020879,3.244509,0.959250,0.376623,0.691787,0.576735
67,"(ch_Citrus Fruit, ch_Biscuit)",(Chardonnay),0.023256,0.183721,0.020930,0.900000,4.898734,1.0,0.016658,8.162791,0.814815,0.112500,0.877493,0.506962
69,(ch_Biscuit),"(ch_Citrus Fruit, Chardonnay)",0.031783,0.053488,0.020930,0.658537,12.311771,1.0,0.019230,2.771927,0.948937,0.325301,0.639240,0.524920
70,"(ch_Biscuit, ch_Green Apple)",(Chardonnay),0.015504,0.183721,0.013953,0.900000,4.898734,1.0,0.011105,8.162791,0.808399,0.075314,0.877493,0.487975
80,"(ch_Black Cherry, ch_Red Fruit)",(Pinot Noir),0.023256,0.089922,0.017829,0.766667,8.525862,1.0,0.015738,3.900332,0.903727,0.186992,0.743612,0.482471
82,"(ch_Black Cherry, ch_Sweet Spice)",(Pinot Noir),0.020155,0.089922,0.013178,0.653846,7.271220,1.0,0.011366,2.629113,0.880212,0.136000,0.619644,0.400199
90,"(ch_Black Fruit, ch_Blackcurrant)",(Cabernet Sauvignon),0.016279,0.067442,0.010078,0.619048,9.178982,1.0,0.008980,2.447965,0.905801,0.136842,0.591497,0.384236
108,"(ch_Black Fruit, ch_Ripe Fruit)",(Malbec),0.024806,0.028682,0.020930,0.843750,29.417230,1.0,0.020219,6.216434,0.990579,0.642857,0.839136,0.786740
111,(ch_Ripe Fruit),"(ch_Black Fruit, Malbec)",0.029457,0.022481,0.020930,0.710526,31.606171,1.0,0.020268,3.376885,0.997752,0.675000,0.703869,0.820780
113,"(ch_Black Fruit, ch_Tobacco)",(Cabernet Sauvignon),0.013178,0.067442,0.009302,0.705882,10.466531,1.0,0.008414,3.170698,0.916536,0.130435,0.684612,0.421907
116,"(ch_Black Fruit, ch_Violet)",(Malbec),0.023256,0.028682,0.020930,0.900000,31.378378,1.0,0.020263,9.713178,0.991182,0.675000,0.897047,0.814865
122,"(ch_Black Plum, ch_Black Pepper)",(Shiraz),0.015504,0.033333,0.011628,0.750000,22.500000,1.0,0.011111,3.866667,0.970604,0.312500,0.741379,0.549419
127,"(ch_Blackcurrant, ch_Black Pepper)",(Shiraz),0.015504,0.033333,0.010078,0.650000,19.500000,1.0,0.009561,2.761905,0.963658,0.260000,0.637931,0.476163
128,"(ch_Black Pepper, ch_Chocolate)",(Shiraz),0.011628,0.033333,0.009302,0.800000,24.000000,1.0,0.008915,4.833333,0.969608,0.260870,0.793103,0.539535
129,"(ch_Vanilla, ch_Black Pepper)",(Shiraz),0.012403,0.033333,0.009302,0.750000,22.500000,1.0,0.008889,3.866667,0.967556,0.255319,0.741379,0.514535
169,"(ch_Black Plum, ch_Blueberry)",(Shiraz),0.020155,0.033333,0.013953,0.692308,20.769231,1.0,0.013282,3.141667,0.971431,0.352941,0.681698,0.555456
171,"(ch_Cedar, ch_Black Plum)",(Cabernet Sauvignon),0.024031,0.067442,0.014729,0.612903,9.087875,1.0,0.013108,2.409109,0.911877,0.191919,0.584909,0.415647
185,"(ch_Black Plum, ch_Raspberry)",(Grenache),0.018605,0.063566,0.011628,0.625000,9.832317,1.0,0.010445,2.497158,0.915324,0.164835,0.599545,0.403963
208,"(ch_Blackberry, ch_Blueberry)",(Shiraz),0.020930,0.033333,0.014729,0.703704,21.111111,1.0,0.014031,3.262500,0.972997,0.372549,0.693487,0.572782
223,"(ch_Blackberry, ch_Red Fruit)",(Pinot Noir),0.018605,0.089922,0.013953,0.750000,8.340517,1.0,0.012281,3.640310,0.896788,0.147541,0.725298,0.452586
237,"(ch_Blueberry, ch_Blackcurrant)",(Shiraz),0.018605,0.033333,0.012403,0.666667,20.000000,1.0,0.011783,2.900000,0.968009,0.313725,0.655172,0.519380
252,"(ch_Blueberry, ch_Chocolate)",(Shiraz),0.015504,0.033333,0.012403,0.800000,24.000000,1.0,0.011886,4.833333,0.973425,0.340426,0.793103,0.586047
254,"(ch_Blueberry, ch_Vanilla)",(Shiraz),0.015504,0.033333,0.010853,0.700000,21.000000,1.0,0.010336,3.222222,0.967379,0.285714,0.689655,0.512791
255,"(ch_Citrus Fruit, ch_Bread)",(Chardonnay),0.033333,0.183721,0.025581,0.767442,4.177215,1.0,0.019457,3.510000,0.786834,0.133603,0.715100,0.453341
259,"(ch_Bread, ch_Cream)",(Chardonnay),0.016279,0.183721,0.014729,0.904762,4.924653,1.0,0.011738,8.570930,0.810128,0.079498,0.883327,0.492465
260,"(ch_Bread, ch_Green Apple)",(Chardonnay),0.025581,0.183721,0.019380,0.757576,4.123514,1.0,0.014680,3.367151,0.777375,0.102041,0.703013,0.431530
261,"(ch_Bread, ch_Hazelnut)",(Chardonnay),0.009302,0.183721,0.009302,1.000000,5.443038,1.0,0.007593,inf,0.823944,0.050633,1.000000,0.525316
262,"(ch_Honey, ch_Bread)",(Chardonnay),0.012403,0.183721,0.010853,0.875000,4.762658,1.0,0.008574,6.530233,0.799955,0.058577,0.846866,0.467036
263,"(ch_Peach, ch_Bread)",(Chardonnay),0.013178,0.183721,0.010853,0.823529,4.482502,1.0,0.008432,4.625581,0.787285,0.058333,0.783811,0.441301
264,"(ch_Bread, ch_Stone Fruit)",(Chardonnay),0.013953,0.183721,0.013178,0.944444,5.140647,1.0,0.010615,14.693023,0.816870,0.071429,0.931940,0.508087
273,"(ch_Butter, ch_Cream)",(Chardonnay),0.015504,0.183721,0.014729,0.950000,5.170886,1.0,0.011880,16.325581,0.819312,0.079832,0.938746,0.515084
279,"(ch_Butter, ch_Green Apple)",(Chardonnay),0.013178,0.183721,0.013178,1.000000,5.443038,1.0,0.010757,inf,0.827180,0.071730,1.000000,0.535865
283,"(ch_Butter, ch_Hazelnut)",(Chardonnay),0.010853,0.183721,0.010853,1.000000,5.443038,1.0,0.008859,inf,0.825235,0.059072,1.000000,0.529536
284,"(ch_Butter, ch_Honey)",(Chardonnay),0.013178,0.183721,0.011628,0.882353,4.802681,1.0,0.009207,6.938372,0.802357,0.062762,0.855874,0.472822
290,"(ch_Butter, ch_Lemon)",(Chardonnay),0.019380,0.183721,0.018605,0.960000,5.225316,1.0,0.015044,20.406977,0.824605,0.100840,0.950997,0.530633
293,"(ch_Butter, ch_Peach)",(Chardonnay),0.023256,0.183721,0.020155,0.866667,4.717300,1.0,0.015882,6.122093,0.806777,0.107884,0.836657,0.488186
295,"(ch_Butter, ch_Stone Fruit)",(Chardonnay),0.010078,0.183721,0.010078,1.000000,5.443038,1.0,0.008226,inf,0.824589,0.054852,1.000000,0.527426
296,"(ch_Butter, ch_Vanilla)",(Chardonnay),0.020930,0.183721,0.020155,0.962963,5.241444,1.0,0.016310,22.039535,0.826512,0.109244,0.954627,0.536334
306,"(ch_Citrus Fruit, ch_Grass)",(Sauvignon Blanc),0.028682,0.079070,0.025581,0.891892,11.279809,1.0,0.023314,8.518605,0.938257,0.311321,0.882610,0.607711

In [98]:
%pip install concepts

Collecting concepts
  Downloading concepts-0.9.2-py2.py3-none-any.whl (31 kB)
Collecting bitsets~=0.7
  Downloading bitsets-0.9.1-py3-none-any.whl (13 kB)
Collecting graphviz~=0.7
  Downloading graphviz-0.21-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 KB 2.4 MB/s eta 0:00:00
Installing collected packages: graphviz, bitsets, concepts
Successfully installed bitsets-0.9.1 concepts-0.9.2 graphviz-0.21
Note: you may need to restart the kernel to use updated packages.

In [99]:
import concepts

In [105]:
context = pd.concat(
    [ohe, ohe3],
    axis=1
).astype(bool)
fca_df_l = context.replace({True: "X", False: ""})

objects = fca_df_l.index.tolist()
attributes = fca_df_l.columns.tolist()
relation = fca_df_l.values.tolist()

# 5. Create FCA context
c = concepts.Context(objects, attributes, relation)

# c = concepts.Context.from_pandas(fca_df_l)

In [106]:
for extent, intent in c:
    print("Objects:", extent)
    print("Attributes:", intent)
    print()

TypeError: 'int' object is not iterable

In [ ]:
style_cols = set(ohe3.columns)
chare_cols = set(ohe.columns)

rules = []

for premise, conclusion in c.lattice.implications:
    if set(premise).issubset(style_cols):
        char_links = set(conclusion).intersection(chare_cols)
        if char_links:
            rules.append((premise, char_links))

rules

#### Caspi / Paspi

In [13]:
import caspailleur as csp

In [19]:
ohe2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1212 entries, 0 to 1289
Data columns (total 23 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Aromatic     1212 non-null   int64
 1   Bold         1212 non-null   int64
 2   Crisp        1212 non-null   int64
 3   Delicate     1212 non-null   int64
 4   Dry          1212 non-null   int64
 5   Elegant      1212 non-null   int64
 6   Floral       1212 non-null   int64
 7   Fresh        1212 non-null   int64
 8   Fruity       1212 non-null   int64
 9   Full Bodied  1212 non-null   int64
 10  Juicy        1212 non-null   int64
 11  Light        1212 non-null   int64
 12  Mellow       1212 non-null   int64
 13  Refreshing   1212 non-null   int64
 14  Rich         1212 non-null   int64
 15  Ripe         1212 non-null   int64
 16  Rounded      1212 non-null   int64
 17  Savoury      1212 non-null   int64
 18  Smooth       1212 non-null   int64
 19  Soft         1212 non-null   int64
 20  Spicy        1212 non-null   int64
 21  Toasty       1212 non-null   int64
 22  Zesty        1212 non-null   int64
dtypes: int64(23)
memory usage: 259.5 KB

In [26]:
PairType = pd.concat([ohe_grape, ohe2], axis=1)

In [27]:

concepts_df = csp.mine_concepts(PairType.astype(bool))

print(concepts_df[['extent', 'intent']].map(', '.join))

                                                       extent  \
concept_id
0           382, 564, 876, 644, 204, 905, 1062, 771, 331, ...
1           564, 1069, 1071, 445, 1043, 289, 1189, 317, 89...
2           270, 285, 1164, 1151, 445, 644, 153, 1043, 188...
3           816, 709, 217, 445, 1043, 456, 862, 905, 824, ...
4           255, 710, 1069, 356, 1071, 153, 1189, 824, 16,...
...                                                       ...
363                                                       667
364                                                      1191
365                                                       875
366                                                       966
367

                                                       intent
concept_id
0
1                                                        Rich
2                                                     Elegant
3                                                       Crisp
4                                                  Chardonnay
...                                                       ...
363         Aromatic, Refreshing, Zesty, Savoury, Fresh, D...
364         Aromatic, Refreshing, Zesty, Savoury, Fresh, D...
365         Aromatic, Refreshing, Zesty, Savoury, Fresh, D...
366         Aromatic, Refreshing, Zesty, Savoury, Fresh, D...
367         Aromatic, Zesty, Furmint, Primitivo, Dry, Spic...

[368 rows x 2 columns]

In [28]:
implications_df = csp.mine_implications(
  PairType.astype(bool), basis_name='Canonical', unit_base=True,
  to_compute=['premise', 'conclusion', 'extent'],
  min_support=2,
)

implications_df

,premise,conclusion,extent
implication_id,,,
0,{Tinta Barroca},Aromatic,"{954, 1250, 480}"
1,{Tinta Barroca},Bold,"{954, 1250, 480}"
2,{Tinta Barroca},Crisp,"{954, 1250, 480}"
3,{Tinta Barroca},Delicate,"{954, 1250, 480}"
4,{Tinta Barroca},Dry,"{954, 1250, 480}"
...,...,...,...
2614,"{Delicate, Dry, Savoury, Full Bodied}",Smooth,"{445, 1043, 893, 970, 868, 1191, 510, 482, 631..."
2615,"{Delicate, Dry, Savoury, Full Bodied}",Soft,"{445, 1043, 893, 970, 868, 1191, 510, 482, 631..."
2616,"{Delicate, Dry, Savoury, Full Bodied}",Spicy,"{445, 1043, 893, 970, 868, 1191, 510, 482, 631..."
2617,"{Delicate, Dry, Savoury, Full Bodied}",Toasty,"{445, 1043, 893, 970, 868, 1191, 510, 482, 631..."
2618,"{Delicate, Dry, Savoury, Full Bodied}",Zesty,"{445, 1043, 893, 970, 868, 1191, 510, 482, 631..."

In [34]:
PairType.to_csv("char_grape.csv", index=True)

In [32]:
concepts_df = csp.mine_concepts(PairType.astype(bool), min_support=5)

# manually define what to show in the nodes of the diagram
new_intent_labels = ('<b>' + concepts_df['new_intent'].map(sorted).map(', '.join) + '</b>').replace('<b></b>', '')
old_intent_labels = (concepts_df['intent'] - concepts_df['new_intent']).map(sorted).map(', '.join)
intent_labels = (new_intent_labels + ';' + old_intent_labels).map(lambda l: ', '.join(l.strip(';').split(';')))
extent_labels = concepts_df['extent'].map(sorted).map(', '.join)

node_labels = intent_labels + '<br><br>' + extent_labels
node_labels = [l.replace(' ', '&nbsp') for l in node_labels] # replace space with non-breakable space for better Mermaid visualisation

diagram_code = csp.io.to_mermaid_diagram(node_labels, concepts_df['previous_concepts'])
print(diagram_code)

flowchart TD
A["<br><br>0,&nbsp1,&nbsp10,&nbsp100,&nbsp1000,&nbsp1001,&nbsp1002,&nbsp1003,&nbsp1004,&nbsp1005,&nbsp1006,&nbsp1007,&nbsp1008,&nbsp1009,&nbsp101,&nbsp1010,&nbsp1011,&nbsp1012,&nbsp1013,&nbsp1014,&nbsp1015,&nbsp1016,&nbsp1017,&nbsp1018,&nbsp1019,&nbsp102,&nbsp1020,&nbsp1021,&nbsp1022,&nbsp1023,&nbsp1024,&nbsp1025,&nbsp1026,&nbsp1027,&nbsp1028,&nbsp1029,&nbsp103,&nbsp1030,&nbsp1031,&nbsp1032,&nbsp1033,&nbsp1034,&nbsp1035,&nbsp1036,&nbsp1037,&nbsp1038,&nbsp1039,&nbsp104,&nbsp1040,&nbsp1041,&nbsp1042,&nbsp1043,&nbsp1044,&nbsp1045,&nbsp1046,&nbsp1047,&nbsp1048,&nbsp1049,&nbsp105,&nbsp1050,&nbsp1051,&nbsp1052,&nbsp1053,&nbsp1054,&nbsp1055,&nbsp1056,&nbsp1057,&nbsp1058,&nbsp1059,&nbsp106,&nbsp1060,&nbsp1061,&nbsp1062,&nbsp1063,&nbsp1064,&nbsp1065,&nbsp1066,&nbsp1067,&nbsp1068,&nbsp1069,&nbsp107,&nbsp1070,&nbsp1071,&nbsp1072,&nbsp1073,&nbsp1074,&nbsp1075,&nbsp1076,&nbsp1077,&nbsp1078,&nbsp1079,&nbsp108,&nbsp1080,&nbsp1081,&nbsp1082,&nbsp1083,&nbsp1084,&nbsp1085,&nbsp1086,&nbsp1087,&nbsp1088,&nbsp1089,&nbsp109,&nbsp1090,&nbsp1091,&nbsp1092,&nbsp1093,&nbsp1094,&nbsp1095,&nbsp1096,&nbsp1097,&nbsp1098,&nbsp1099,&nbsp11,&nbsp110,&nbsp1100,&nbsp1101,&nbsp1102,&nbsp1103,&nbsp1104,&nbsp1105,&nbsp1106,&nbsp1107,&nbsp1108,&nbsp1109,&nbsp111,&nbsp1110,&nbsp1111,&nbsp1112,&nbsp1113,&nbsp1114,&nbsp1115,&nbsp1116,&nbsp1117,&nbsp1118,&nbsp1119,&nbsp112,&nbsp1120,&nbsp1121,&nbsp1122,&nbsp1123,&nbsp1124,&nbsp1125,&nbsp1126,&nbsp1127,&nbsp1128,&nbsp1129,&nbsp113,&nbsp1130,&nbsp1131,&nbsp1132,&nbsp1133,&nbsp1134,&nbsp1135,&nbsp1136,&nbsp1137,&nbsp1138,&nbsp1139,&nbsp114,&nbsp1140,&nbsp1141,&nbsp1142,&nbsp1143,&nbsp1144,&nbsp1145,&nbsp1146,&nbsp1147,&nbsp1148,&nbsp1149,&nbsp115,&nbsp1150,&nbsp1151,&nbsp1152,&nbsp1153,&nbsp1154,&nbsp1155,&nbsp1156,&nbsp1157,&nbsp1158,&nbsp1159,&nbsp116,&nbsp1160,&nbsp1161,&nbsp1162,&nbsp1163,&nbsp1164,&nbsp1165,&nbsp1166,&nbsp1167,&nbsp1168,&nbsp1169,&nbsp117,&nbsp1170,&nbsp1171,&nbsp1172,&nbsp1173,&nbsp1174,&nbsp1175,&nbsp1176,&nbsp1177,&nbsp1178,&nbsp1179,&nbsp118,&nbsp1180,&nbsp1181,&nbsp1182,&nbsp1183,&nbsp1184,&nbsp1185,&nbsp1186,&nbsp1187,&nbsp1188,&nbsp1189,&nbsp119,&nbsp1190,&nbsp1191,&nbsp1192,&nbsp1193,&nbsp1194,&nbsp1195,&nbsp1196,&nbsp1197,&nbsp1198,&nbsp1199,&nbsp12,&nbsp120,&nbsp1200,&nbsp1201,&nbsp1202,&nbsp1203,&nbsp1204,&nbsp1205,&nbsp1206,&nbsp1207,&nbsp1208,&nbsp1209,&nbsp121,&nbsp1210,&nbsp1211,&nbsp1212,&nbsp1213,&nbsp1214,&nbsp1215,&nbsp1216,&nbsp1217,&nbsp1218,&nbsp1219,&nbsp122,&nbsp1220,&nbsp1221,&nbsp1222,&nbsp1223,&nbsp1224,&nbsp1225,&nbsp1226,&nbsp1227,&nbsp1228,&nbsp1229,&nbsp123,&nbsp1230,&nbsp1231,&nbsp1232,&nbsp1233,&nbsp1234,&nbsp1235,&nbsp1236,&nbsp1237,&nbsp1238,&nbsp1239,&nbsp124,&nbsp1240,&nbsp1241,&nbsp1242,&nbsp1243,&nbsp1244,&nbsp1245,&nbsp1246,&nbsp1247,&nbsp1248,&nbsp1249,&nbsp125,&nbsp1250,&nbsp1251,&nbsp1252,&nbsp1253,&nbsp1254,&nbsp1255,&nbsp1256,&nbsp1257,&nbsp1258,&nbsp1259,&nbsp126,&nbsp1260,&nbsp1261,&nbsp1262,&nbsp1263,&nbsp1264,&nbsp1265,&nbsp1266,&nbsp1267,&nbsp1268,&nbsp1269,&nbsp127,&nbsp1270,&nbsp1271,&nbsp1272,&nbsp1273,&nbsp1274,&nbsp1275,&nbsp1276,&nbsp1277,&nbsp1278,&nbsp1279,&nbsp128,&nbsp1280,&nbsp1281,&nbsp1282,&nbsp1283,&nbsp1284,&nbsp1285,&nbsp1286,&nbsp1287,&nbsp1288,&nbsp1289,&nbsp129,&nbsp13,&nbsp130,&nbsp131,&nbsp132,&nbsp133,&nbsp134,&nbsp135,&nbsp136,&nbsp137,&nbsp138,&nbsp139,&nbsp14,&nbsp140,&nbsp141,&nbsp142,&nbsp143,&nbsp144,&nbsp145,&nbsp146,&nbsp147,&nbsp148,&nbsp149,&nbsp15,&nbsp150,&nbsp151,&nbsp152,&nbsp153,&nbsp154,&nbsp155,&nbsp156,&nbsp157,&nbsp158,&nbsp159,&nbsp16,&nbsp160,&nbsp161,&nbsp162,&nbsp163,&nbsp164,&nbsp165,&nbsp166,&nbsp167,&nbsp168,&nbsp169,&nbsp17,&nbsp170,&nbsp171,&nbsp172,&nbsp173,&nbsp174,&nbsp175,&nbsp176,&nbsp177,&nbsp178,&nbsp179,&nbsp18,&nbsp180,&nbsp181,&nbsp182,&nbsp183,&nbsp184,&nbsp185,&nbsp186,&nbsp187,&nbsp188,&nbsp189,&nbsp19,&nbsp190,&nbsp191,&nbsp192,&nbsp193,&nbsp194,&nbsp195,&nbsp196,&nbsp197,&nbsp198,&nbsp199,&nbsp2,&nbsp20,&nbsp200,&nbsp201,&nbsp202,&nbsp203,&nbsp204,&nbsp205,&nbsp206,&nbsp207,&nbsp208,&nbsp209,&nbsp21,&nbsp210,&nbsp211,&nbsp212,&nbsp213,&nbsp214,&nbsp215,&nbsp216,&nbsp217,&nbsp218,&nbsp219,&nbsp22,&nbsp220,&nbsp221,&nbsp222,&nbsp223,&nbsp224,&nbsp225,&nbsp226,&nbsp227,&nbsp228,&nbsp229,&nbsp23,&nbsp230,&nbsp231,&nbsp232,&nbsp233,&nbsp234,&nbsp235,&nbsp236,&nbsp237,&nbsp238,&nbsp239,&nbsp24,&nbsp240,&nbsp241,&nbsp242,&nbsp243,&nbsp244,&nbsp245,&nbsp246,&nbsp247,&nbsp248,&nbsp249,&nbsp25,&nbsp250,&nbsp251,&nbsp252,&nbsp253,&nbsp254,&nbsp255,&nbsp256,&nbsp257,&nbsp258,&nbsp259,&nbsp26,&nbsp260,&nbsp261,&nbsp262,&nbsp263,&nbsp264,&nbsp265,&nbsp266,&nbsp267,&nbsp268,&nbsp269,&nbsp27,&nbsp270,&nbsp271,&nbsp272,&nbsp273,&nbsp274,&nbsp275,&nbsp276,&nbsp277,&nbsp278,&nbsp279,&nbsp28,&nbsp280,&nbsp281,&nbsp282,&nbsp283,&nbsp284,&nbsp285,&nbsp286,&nbsp287,&nbsp288,&nbsp289,&nbsp29,&nbsp290,&nbsp291,&nbsp292,&nbsp293,&nbsp294,&nbsp295,&nbsp296,&nbsp297,&nbsp298,&nbsp299,&nbsp3,&nbsp30,&nbsp300,&nbsp301,&nbsp302,&nbsp303,&nbsp304,&nbsp305,&nbsp306,&nbsp307,&nbsp308,&nbsp309,&nbsp31,&nbsp310,&nbsp311,&nbsp312,&nbsp313,&nbsp314,&nbsp315,&nbsp316,&nbsp317,&nbsp318,&nbsp319,&nbsp32,&nbsp320,&nbsp321,&nbsp322,&nbsp323,&nbsp324,&nbsp325,&nbsp326,&nbsp327,&nbsp328,&nbsp329,&nbsp33,&nbsp330,&nbsp331,&nbsp332,&nbsp333,&nbsp334,&nbsp335,&nbsp336,&nbsp337,&nbsp338,&nbsp339,&nbsp34,&nbsp340,&nbsp341,&nbsp342,&nbsp343,&nbsp344,&nbsp345,&nbsp346,&nbsp347,&nbsp348,&nbsp349,&nbsp35,&nbsp350,&nbsp351,&nbsp352,&nbsp353,&nbsp354,&nbsp355,&nbsp356,&nbsp357,&nbsp358,&nbsp359,&nbsp36,&nbsp360,&nbsp361,&nbsp362,&nbsp363,&nbsp364,&nbsp365,&nbsp366,&nbsp367,&nbsp368,&nbsp369,&nbsp37,&nbsp370,&nbsp371,&nbsp372,&nbsp373,&nbsp374,&nbsp375,&nbsp376,&nbsp377,&nbsp378,&nbsp379,&nbsp38,&nbsp380,&nbsp381,&nbsp382,&nbsp383,&nbsp384,&nbsp385,&nbsp386,&nbsp387,&nbsp388,&nbsp389,&nbsp39,&nbsp390,&nbsp391,&nbsp392,&nbsp393,&nbsp394,&nbsp395,&nbsp396,&nbsp397,&nbsp398,&nbsp399,&nbsp4,&nbsp40,&nbsp400,&nbsp401,&nbsp402,&nbsp403,&nbsp404,&nbsp405,&nbsp406,&nbsp407,&nbsp408,&nbsp409,&nbsp41,&nbsp410,&nbsp411,&nbsp412,&nbsp413,&nbsp414,&nbsp415,&nbsp416,&nbsp417,&nbsp418,&nbsp419,&nbsp42,&nbsp420,&nbsp421,&nbsp422,&nbsp423,&nbsp424,&nbsp425,&nbsp426,&nbsp427,&nbsp428,&nbsp429,&nbsp43,&nbsp430,&nbsp431,&nbsp432,&nbsp433,&nbsp434,&nbsp435,&nbsp436,&nbsp437,&nbsp438,&nbsp439,&nbsp44,&nbsp440,&nbsp441,&nbsp442,&nbsp443,&nbsp444,&nbsp445,&nbsp446,&nbsp447,&nbsp448,&nbsp449,&nbsp45,&nbsp450,&nbsp451,&nbsp452,&nbsp453,&nbsp454,&nbsp455,&nbsp456,&nbsp457,&nbsp458,&nbsp459,&nbsp46,&nbsp460,&nbsp461,&nbsp462,&nbsp463,&nbsp464,&nbsp465,&nbsp466,&nbsp467,&nbsp468,&nbsp469,&nbsp47,&nbsp470,&nbsp471,&nbsp472,&nbsp473,&nbsp474,&nbsp475,&nbsp476,&nbsp477,&nbsp478,&nbsp479,&nbsp48,&nbsp480,&nbsp481,&nbsp482,&nbsp483,&nbsp484,&nbsp485,&nbsp486,&nbsp487,&nbsp488,&nbsp489,&nbsp49,&nbsp490,&nbsp491,&nbsp492,&nbsp493,&nbsp494,&nbsp495,&nbsp496,&nbsp497,&nbsp498,&nbsp499,&nbsp5,&nbsp50,&nbsp500,&nbsp501,&nbsp502,&nbsp503,&nbsp504,&nbsp505,&nbsp506,&nbsp507,&nbsp508,&nbsp509,&nbsp51,&nbsp510,&nbsp511,&nbsp512,&nbsp513,&nbsp514,&nbsp515,&nbsp516,&nbsp517,&nbsp518,&nbsp519,&nbsp52,&nbsp520,&nbsp521,&nbsp522,&nbsp523,&nbsp524,&nbsp525,&nbsp526,&nbsp527,&nbsp528,&nbsp529,&nbsp53,&nbsp530,&nbsp531,&nbsp532,&nbsp533,&nbsp534,&nbsp535,&nbsp536,&nbsp537,&nbsp538,&nbsp539,&nbsp54,&nbsp540,&nbsp541,&nbsp542,&nbsp543,&nbsp544,&nbsp545,&nbsp546,&nbsp547,&nbsp548,&nbsp549,&nbsp55,&nbsp550,&nbsp551,&nbsp552,&nbsp553,&nbsp554,&nbsp555,&nbsp556,&nbsp557,&nbsp558,&nbsp559,&nbsp56,&nbsp560,&nbsp561,&nbsp562,&nbsp563,&nbsp564,&nbsp565,&nbsp566,&nbsp567,&nbsp568,&nbsp569,&nbsp57,&nbsp570,&nbsp571,&nbsp572,&nbsp573,&nbsp574,&nbsp575,&nbsp576,&nbsp577,&nbsp578,&nbsp579,&nbsp58,&nbsp580,&nbsp581,&nbsp582,&nbsp583,&nbsp584,&nbsp585,&nbsp586,&nbsp587,&nbsp588,&nbsp589,&nbsp59,&nbsp590,&nbsp591,&nbsp592,&nbsp593,&nbsp594,&nbsp595,&nbsp596,&nbsp597,&nbsp598,&nbsp599,&nbsp6,&nbsp60,&nbsp600,&nbsp601,&nbsp602,&nbsp603,&nbsp604,&nbsp605,&nbsp606,&nbsp607,&nbsp608,&nbsp609,&nbsp61,&nbsp610,&nbsp611,&nbsp612,&nbsp613,&nbsp614,&nbsp615,&nbsp616,&nbsp617,&nbsp618,&nbsp619,&nbsp62,&nbsp620,&nbsp621,&nbsp622,&nbsp623,&nbsp624,&nbsp625,&nbsp626,&nbsp627,&nbsp628,&nbsp629,&nbsp63,&nbsp630,&nbsp631,&nbsp632,&nbsp633,&nbsp634,&nbsp635,&nbsp636,&nbsp637,&nbsp638,&nbsp639,&nbsp64,&nbsp640,&nbsp641,&nbsp642,&nbsp643,&nbsp644,&nbsp645,&nbsp646,&nbsp647,&nbsp648,&nbsp649,&nbsp65,&nbsp650,&nbsp651,&nbsp652,&nbsp653,&nbsp654,&nbsp655,&nbsp656,&nbsp657,&nbsp658,&nbsp659,&nbsp66,&nbsp660,&nbsp661,&nbsp662,&nbsp663,&nbsp664,&nbsp665,&nbsp666,&nbsp667,&nbsp668,&nbsp669,&nbsp67,&nbsp670,&nbsp671,&nbsp672,&nbsp673,&nbsp674,&nbsp675,&nbsp676,&nbsp677,&nbsp678,&nbsp679,&nbsp68,&nbsp680,&nbsp681,&nbsp682,&nbsp683,&nbsp684,&nbsp685,&nbsp686,&nbsp687,&nbsp688,&nbsp689,&nbsp69,&nbsp690,&nbsp691,&nbsp692,&nbsp693,&nbsp694,&nbsp695,&nbsp696,&nbsp697,&nbsp698,&nbsp699,&nbsp7,&nbsp70,&nbsp700,&nbsp701,&nbsp702,&nbsp703,&nbsp704,&nbsp705,&nbsp706,&nbsp707,&nbsp708,&nbsp709,&nbsp71,&nbsp710,&nbsp711,&nbsp712,&nbsp713,&nbsp714,&nbsp715,&nbsp716,&nbsp717,&nbsp718,&nbsp719,&nbsp72,&nbsp720,&nbsp721,&nbsp722,&nbsp723,&nbsp724,&nbsp725,&nbsp726,&nbsp727,&nbsp728,&nbsp729,&nbsp73,&nbsp730,&nbsp731,&nbsp732,&nbsp733,&nbsp734,&nbsp735,&nbsp736,&nbsp737,&nbsp738,&nbsp739,&nbsp74,&nbsp740,&nbsp741,&nbsp742,&nbsp743,&nbsp744,&nbsp745,&nbsp746,&nbsp747,&nbsp748,&nbsp749,&nbsp75,&nbsp750,&nbsp751,&nbsp752,&nbsp753,&nbsp754,&nbsp755,&nbsp756,&nbsp757,&nbsp758,&nbsp759,&nbsp76,&nbsp760,&nbsp761,&nbsp762,&nbsp763,&nbsp764,&nbsp765,&nbsp766,&nbsp767,&nbsp768,&nbsp769,&nbsp77,&nbsp770,&nbsp771,&nbsp772,&nbsp773,&nbsp774,&nbsp775,&nbsp776,&nbsp777,&nbsp778,&nbsp779,&nbsp78,&nbsp780,&nbsp781,&nbsp782,&nbsp783,&nbsp784,&nbsp785,&nbsp786,&nbsp787,&nbsp788,&nbsp789,&nbsp79,&nbsp790,&nbsp791,&nbsp792,&nbsp793,&nbsp794,&nbsp795,&nbsp796,&nbsp797,&nbsp798,&nbsp799,&nbsp8,&nbsp80,&nbsp800,&nbsp801,&nbsp802,&nbsp803,&nbsp804,&nbsp805,&nbsp806,&nbsp807,&nbsp808,&nbsp809,&nbsp81,&nbsp810,&nbsp811,&nbsp812,&nbsp813,&nbsp814,&nbsp815,&nbsp816,&nbsp817,&nbsp818,&nbsp819,&nbsp82,&nbsp820,&nbsp821,&nbsp822,&nbsp823,&nbsp824,&nbsp825,&nbsp826,&nbsp827,&nbsp828,&nbsp829,&nbsp83,&nbsp830,&nbsp831,&nbsp832,&nbsp833,&nbsp834,&nbsp835,&nbsp836,&nbsp837,&nbsp838,&nbsp839,&nbsp84,&nbsp840,&nbsp841,&nbsp842,&nbsp843,&nbsp844,&nbsp845,&nbsp846,&nbsp847,&nbsp848,&nbsp849,&nbsp85,&nbsp850,&nbsp851,&nbsp852,&nbsp853,&nbsp854,&nbsp855,&nbsp856,&nbsp857,&nbsp858,&nbsp859,&nbsp86,&nbsp860,&nbsp861,&nbsp862,&nbsp863,&nbsp864,&nbsp865,&nbsp866,&nbsp867,&nbsp868,&nbsp869,&nbsp87,&nbsp870,&nbsp871,&nbsp872,&nbsp873,&nbsp874,&nbsp875,&nbsp876,&nbsp877,&nbsp878,&nbsp879,&nbsp88,&nbsp880,&nbsp881,&nbsp882,&nbsp883,&nbsp884,&nbsp885,&nbsp886,&nbsp887,&nbsp888,&nbsp889,&nbsp89,&nbsp890,&nbsp891,&nbsp892,&nbsp893,&nbsp894,&nbsp895,&nbsp896,&nbsp897,&nbsp898,&nbsp899,&nbsp9,&nbsp90,&nbsp900,&nbsp901,&nbsp902,&nbsp903,&nbsp904,&nbsp905,&nbsp906,&nbsp907,&nbsp908,&nbsp909,&nbsp91,&nbsp910,&nbsp911,&nbsp912,&nbsp913,&nbsp914,&nbsp915,&nbsp916,&nbsp917,&nbsp918,&nbsp919,&nbsp92,&nbsp920,&nbsp921,&nbsp922,&nbsp923,&nbsp924,&nbsp925,&nbsp926,&nbsp927,&nbsp928,&nbsp929,&nbsp93,&nbsp930,&nbsp931,&nbsp932,&nbsp933,&nbsp934,&nbsp935,&nbsp936,&nbsp937,&nbsp938,&nbsp939,&nbsp94,&nbsp940,&nbsp941,&nbsp942,&nbsp943,&nbsp944,&nbsp945,&nbsp946,&nbsp947,&nbsp948,&nbsp949,&nbsp95,&nbsp950,&nbsp951,&nbsp952,&nbsp953,&nbsp954,&nbsp955,&nbsp956,&nbsp957,&nbsp958,&nbsp959,&nbsp96,&nbsp960,&nbsp961,&nbsp962,&nbsp963,&nbsp964,&nbsp965,&nbsp966,&nbsp967,&nbsp968,&nbsp969,&nbsp97,&nbsp970,&nbsp971,&nbsp972,&nbsp973,&nbsp974,&nbsp975,&nbsp976,&nbsp977,&nbsp978,&nbsp979,&nbsp98,&nbsp980,&nbsp981,&nbsp982,&nbsp983,&nbsp984,&nbsp985,&nbsp986,&nbsp987,&nbsp988,&nbsp989,&nbsp99,&nbsp990,&nbsp991,&nbsp992,&nbsp993,&nbsp994,&nbsp995,&nbsp996,&nbsp997,&nbsp998,&nbsp999"];
B["<b>Rich</b><br><br>0,&nbsp1,&nbsp1004,&nbsp1005,&nbsp1008,&nbsp1009,&nbsp1010,&nbsp1011,&nbsp1013,&nbsp1017,&nbsp1020,&nbsp1021,&nbsp1028,&nbsp1030,&nbsp1031,&nbsp1037,&nbsp104,&nbsp1041,&nbsp1043,&nbsp1044,&nbsp1050,&nbsp1056,&nbsp1066,&nbsp1068,&nbsp1069,&nbsp1070,&nbsp1071,&nbsp1073,&nbsp1075,&nbsp1077,&nbsp1082,&nbsp1087,&nbsp1090,&nbsp1093,&nbsp1096,&nbsp1099,&nbsp1100,&nbsp1102,&nbsp111,&nbsp1111,&nbsp1117,&nbsp1118,&nbsp1119,&nbsp1122,&nbsp113,&nbsp1130,&nbsp1134,&nbsp1135,&nbsp1136,&nbsp114,&nbsp1148,&nbsp1157,&nbsp1158,&nbsp1163,&nbsp1168,&nbsp1169,&nbsp1171,&nbsp1175,&nbsp1182,&nbsp1183,&nbsp1184,&nbsp1185,&nbsp1187,&nbsp1189,&nbsp1191,&nbsp1192,&nbsp1193,&nbsp1198,&nbsp1203,&nbsp1205,&nbsp1208,&nbsp1212,&nbsp1213,&nbsp1214,&nbsp1219,&nbsp122,&nbsp1228,&nbsp124,&nbsp1245,&nbsp1246,&nbsp1247,&nbsp1249,&nbsp1250,&nbsp1253,&nbsp1256,&nbsp1261,&nbsp1263,&nbsp1272,&nbsp1275,&nbsp1279,&nbsp128,&nbsp1280,&nbsp1283,&nbsp133,&nbsp141,&nbsp154,&nbsp168,&nbsp17,&nbsp189,&nbsp191,&nbsp201,&nbsp22,&nbsp228,&nbsp233,&nbsp237,&nbsp240,&nbsp243,&nbsp246,&nbsp252,&nbsp267,&nbsp268,&nbsp269,&nbsp273,&nbsp276,&nbsp279,&nbsp281,&nbsp286,&nbsp289,&nbsp295,&nbsp298,&nbsp30,&nbsp302,&nbsp306,&nbsp316,&nbsp317,&nbsp318,&nbsp319,&nbsp323,&nbsp33,&nbsp339,&nbsp340,&nbsp341,&nbsp351,&nbsp353,&nbsp359,&nbsp360,&nbsp365,&nbsp372,&nbsp373,&nbsp375,&nbsp377,&nbsp378,&nbsp395,&nbsp396,&nbsp417,&nbsp422,&nbsp424,&nbsp432,&nbsp439,&nbsp445,&nbsp452,&nbsp458,&nbsp460,&nbsp464,&nbsp477,&nbsp478,&nbsp480,&nbsp482,&nbsp491,&nbsp492,&nbsp495,&nbsp496,&nbsp497,&nbsp499,&nbsp5,&nbsp502,&nbsp506,&nbsp507,&nbsp510,&nbsp512,&nbsp514,&nbsp518,&nbsp523,&nbsp534,&nbsp539,&nbsp540,&nbsp556,&nbsp561,&nbsp564,&nbsp577,&nbsp579,&nbsp581,&nbsp586,&nbsp590,&nbsp594,&nbsp602,&nbsp61,&nbsp615,&nbsp619,&nbsp621,&nbsp631,&nbsp642,&nbsp645,&nbsp646,&nbsp65,&nbsp654,&nbsp663,&nbsp664,&nbsp667,&nbsp669,&nbsp67,&nbsp671,&nbsp68,&nbsp684,&nbsp690,&nbsp692,&nbsp693,&nbsp7,&nbsp707,&nbsp708,&nbsp712,&nbsp714,&nbsp719,&nbsp721,&nbsp73,&nbsp732,&nbsp737,&nbsp738,&nbsp753,&nbsp755,&nbsp758,&nbsp759,&nbsp762,&nbsp763,&nbsp768,&nbsp780,&nbsp791,&nbsp792,&nbsp793,&nbsp794,&nbsp799,&nbsp8,&nbsp822,&nbsp860,&nbsp868,&nbsp871,&nbsp873,&nbsp874,&nbsp875,&nbsp884,&nbsp887,&nbsp892,&nbsp893,&nbsp894,&nbsp896,&nbsp897,&nbsp899,&nbsp9,&nbsp902,&nbsp904,&nbsp908,&nbsp915,&nbsp916,&nbsp917,&nbsp919,&nbsp930,&nbsp936,&nbsp940,&nbsp942,&nbsp944,&nbsp945,&nbsp952,&nbsp953,&nbsp954,&nbsp955,&nbsp957,&nbsp958,&nbsp959,&nbsp960,&nbsp962,&nbsp964,&nbsp966,&nbsp968,&nbsp970,&nbsp972,&nbsp973,&nbsp984,&nbsp987,&nbsp99,&nbsp990,&nbsp991,&nbsp992,&nbsp996,&nbsp997"];
C["<b>Elegant</b><br><br>1004,&nbsp1017,&nbsp1020,&nbsp1023,&nbsp1036,&nbsp104,&nbsp1042,&nbsp1043,&nbsp1044,&nbsp1047,&nbsp1049,&nbsp105,&nbsp1050,&nbsp1058,&nbsp1062,&nbsp1063,&nbsp1065,&nbsp1067,&nbsp1080,&nbsp1081,&nbsp1082,&nbsp1083,&nbsp1085,&nbsp1087,&nbsp1088,&nbsp1094,&nbsp1096,&nbsp1101,&nbsp1102,&nbsp1129,&nbsp1131,&nbsp1137,&nbsp1138,&nbsp1141,&nbsp1144,&nbsp1151,&nbsp1155,&nbsp1164,&nbsp1170,&nbsp1171,&nbsp1173,&nbsp1178,&nbsp1182,&nbsp1183,&nbsp1184,&nbsp1185,&nbsp1190,&nbsp1191,&nbsp1193,&nbsp12,&nbsp1202,&nbsp1203,&nbsp1209,&nbsp121,&nbsp1210,&nbsp1221,&nbsp1229,&nbsp1232,&nbsp1234,&nbsp1238,&nbsp124,&nbsp1240,&nbsp1244,&nbsp1249,&nbsp1250,&nbsp1252,&nbsp1255,&nbsp1261,&nbsp1263,&nbsp1267,&nbsp1273,&nbsp1283,&nbsp130,&nbsp132,&nbsp146,&nbsp148,&nbsp153,&nbsp164,&nbsp165,&nbsp181,&nbsp185,&nbsp188,&nbsp207,&nbsp229,&nbsp235,&nbsp251,&nbsp252,&nbsp254,&nbsp256,&nbsp264,&nbsp265,&nbsp270,&nbsp275,&nbsp282,&nbsp283,&nbsp285,&nbsp292,&nbsp295,&nbsp298,&nbsp307,&nbsp308,&nbsp309,&nbsp310,&nbsp312,&nbsp314,&nbsp315,&nbsp320,&nbsp321,&nbsp323,&nbsp329,&nbsp334,&nbsp338,&nbsp350,&nbsp354,&nbsp357,&nbsp359,&nbsp367,&nbsp370,&nbsp393,&nbsp397,&nbsp402,&nbsp406,&nbsp409,&nbsp411,&nbsp412,&nbsp422,&nbsp425,&nbsp431,&nbsp433,&nbsp438,&nbsp441,&nbsp445,&nbsp447,&nbsp457,&nbsp458,&nbsp460,&nbsp463,&nbsp467,&nbsp469,&nbsp477,&nbsp478,&nbsp480,&nbsp482,&nbsp487,&nbsp491,&nbsp492,&nbsp495,&nbsp496,&nbsp5,&nbsp501,&nbsp502,&nbsp505,&nbsp507,&nbsp508,&nbsp510,&nbsp512,&nbsp513,&nbsp521,&nbsp541,&nbsp542,&nbsp55,&nbsp561,&nbsp567,&nbsp568,&nbsp578,&nbsp58,&nbsp584,&nbsp586,&nbsp59,&nbsp595,&nbsp596,&nbsp597,&nbsp598,&nbsp599,&nbsp60,&nbsp601,&nbsp603,&nbsp605,&nbsp606,&nbsp607,&nbsp609,&nbsp620,&nbsp622,&nbsp623,&nbsp631,&nbsp632,&nbsp633,&nbsp634,&nbsp637,&nbsp638,&nbsp644,&nbsp647,&nbsp653,&nbsp657,&nbsp66,&nbsp662,&nbsp666,&nbsp667,&nbsp668,&nbsp669,&nbsp677,&nbsp678,&nbsp686,&nbsp687,&nbsp689,&nbsp698,&nbsp7,&nbsp702,&nbsp703,&nbsp704,&nbsp713,&nbsp714,&nbsp717,&nbsp72,&nbsp722,&nbsp723,&nbsp735,&nbsp743,&nbsp745,&nbsp748,&nbsp75,&nbsp754,&nbsp755,&nbsp771,&nbsp777,&nbsp787,&nbsp794,&nbsp797,&nbsp80,&nbsp805,&nbsp814,&nbsp82,&nbsp822,&nbsp828,&nbsp835,&nbsp855,&nbsp856,&nbsp860,&nbsp861,&nbsp863,&nbsp865,&nbsp866,&nbsp868,&nbsp871,&nbsp872,&nbsp873,&nbsp875,&nbsp879,&nbsp884,&nbsp89,&nbsp890,&nbsp891,&nbsp893,&nbsp919,&nbsp920,&nbsp928,&nbsp929,&nbsp94,&nbsp954,&nbsp959,&nbsp96,&nbsp960,&nbsp962,&nbsp964,&nbsp966,&nbsp968,&nbsp970,&nbsp972,&nbsp973,&nbsp974,&nbsp977,&nbsp980,&nbsp986,&nbsp989,&nbsp99,&nbsp991,&nbsp992"];
D["<b>Crisp</b><br><br>10,&nbsp100,&nbsp1001,&nbsp1003,&nbsp1004,&nbsp1017,&nbsp102,&nbsp1020,&nbsp103,&nbsp1033,&nbsp104,&nbsp1043,&nbsp1044,&nbsp1050,&nbsp1055,&nbsp106,&nbsp107,&nbsp1082,&nbsp1084,&nbsp1087,&nbsp1095,&nbsp1096,&nbsp11,&nbsp1102,&nbsp1103,&nbsp1112,&nbsp1121,&nbsp1145,&nbsp115,&nbsp116,&nbsp1171,&nbsp118,&nbsp1181,&nbsp1182,&nbsp1183,&nbsp1184,&nbsp1185,&nbsp1191,&nbsp1193,&nbsp1203,&nbsp1225,&nbsp1235,&nbsp124,&nbsp1249,&nbsp125,&nbsp1250,&nbsp1257,&nbsp1258,&nbsp1261,&nbsp1263,&nbsp1274,&nbsp1276,&nbsp1277,&nbsp1281,&nbsp1283,&nbsp14,&nbsp140,&nbsp142,&nbsp16,&nbsp179,&nbsp180,&nbsp190,&nbsp192,&nbsp196,&nbsp197,&nbsp199,&nbsp2,&nbsp21,&nbsp212,&nbsp216,&nbsp217,&nbsp227,&nbsp23,&nbsp236,&nbsp239,&nbsp24,&nbsp241,&nbsp248,&nbsp249,&nbsp25,&nbsp252,&nbsp253,&nbsp26,&nbsp271,&nbsp277,&nbsp291,&nbsp294,&nbsp295,&nbsp296,&nbsp297,&nbsp298,&nbsp304,&nbsp31,&nbsp323,&nbsp324,&nbsp331,&nbsp335,&nbsp337,&nbsp343,&nbsp344,&nbsp345,&nbsp35,&nbsp358,&nbsp359,&nbsp36,&nbsp362,&nbsp368,&nbsp376,&nbsp380,&nbsp390,&nbsp403,&nbsp410,&nbsp414,&nbsp418,&nbsp42,&nbsp422,&nbsp43,&nbsp430,&nbsp434,&nbsp435,&nbsp445,&nbsp446,&nbsp449,&nbsp450,&nbsp456,&nbsp458,&nbsp46,&nbsp460,&nbsp47,&nbsp474,&nbsp477,&nbsp478,&nbsp480,&nbsp482,&nbsp491,&nbsp492,&nbsp495,&nbsp496,&nbsp5,&nbsp50,&nbsp502,&nbsp504,&nbsp507,&nbsp510,&nbsp512,&nbsp53,&nbsp538,&nbsp549,&nbsp558,&nbsp56,&nbsp561,&nbsp582,&nbsp586,&nbsp614,&nbsp62,&nbsp624,&nbsp63,&nbsp630,&nbsp631,&nbsp655,&nbsp667,&nbsp669,&nbsp680,&nbsp681,&nbsp69,&nbsp7,&nbsp701,&nbsp709,&nbsp714,&nbsp724,&nbsp729,&nbsp730,&nbsp755,&nbsp756,&nbsp76,&nbsp767,&nbsp769,&nbsp770,&nbsp772,&nbsp773,&nbsp778,&nbsp784,&nbsp789,&nbsp794,&nbsp796,&nbsp800,&nbsp801,&nbsp807,&nbsp811,&nbsp812,&nbsp816,&nbsp817,&nbsp821,&nbsp822,&nbsp824,&nbsp825,&nbsp826,&nbsp827,&nbsp83,&nbsp84,&nbsp843,&nbsp845,&nbsp846,&nbsp847,&nbsp850,&nbsp851,&nbsp852,&nbsp853,&nbsp860,&nbsp862,&nbsp867,&nbsp868,&nbsp871,&nbsp873,&nbsp875,&nbsp881,&nbsp884,&nbsp889,&nbsp893,&nbsp895,&nbsp898,&nbsp90,&nbsp901,&nbsp905,&nbsp906,&nbsp909,&nbsp910,&nbsp911,&nbsp912,&nbsp913,&nbsp914,&nbsp919,&nbsp922,&nbsp923,&nbsp924,&nbsp941,&nbsp943,&nbsp948,&nbsp954,&nbsp959,&nbsp960,&nbsp962,&nbsp964,&nbsp966,&nbsp968,&nbsp97,&nbsp970,&nbsp971,&nbsp972,&nbsp973,&nbsp976,&nbsp98,&nbsp981,&nbsp983,&nbsp988,&nbsp99,&nbsp991,&nbsp992,&nbsp995"];

### Regions

In [42]:
df_wine[df_wine['Grape'] == 'Shiraz']

,Title,Description,Price,Capacity,Grape,Secondary Grape Varieties,Closure,Country,Unit,Characteristics,Per bottle / case / each,Type,ABV,Region,Style,Vintage,Appellation,Capacity_L
19,"Two Hands 'Angels' Share' Shiraz 2021/22, McLa...",Two Hands successfully prove that not all Auss...,£21.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.8,"Vanilla, Black Fruit, Black Pepper, Blackcurra...",per bottle,Red,ABV 14.40%,South Australia,Bold & Spicy,2022,Mclaren Vale,0.75
54,"Two Hands 'Tenacity' Old Vine Shiraz 2021/22, ...",Two Hands founders Michael Twelftree and Richa...,£14.99 per bottle,75CL,Shiraz,NaN,Natural Cork,Australia,10.7,"Vanilla, Black Pepper, Black Plum, Blackberry,...",per bottle,Red,ABV 14.20%,South Australia,Bold & Spicy,2022,Mclaren Vale,0.75
70,"Jim Barry 'The Lodge Hill' Shiraz 2020/21, Cla...",Clare Valley has a relatively cool climate. It...,£15.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.5,"Vanilla, Black Plum, Blackberry, Blackcurrant,...",per bottle,Red,ABV 14.00%,South Australia,Bold & Spicy,2021,Clare Valley,0.75
78,"Peter Lehmann 'The Barossan' Shiraz 2019/20, B...","With rolling hills, hot, dry summers and some ...",£18.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.9,"Smoke, Black Pepper, Black Plum, Blackberry, B...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2020,Barossa Valley,0.75
163,"Casella 'PepperBox' Shiraz 2020/21, South East...","In 1820, in the small Sicilian town of Giarre,...",£11.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.5,"Black Pepper, Black Plum, Spice, Vanilla",per bottle,Red,ABV 14.00%,South East Australia,Bold & Spicy,2021,NaN,0.75
172,"Boekenhoutskloof ‘The Wolftrap’ Shiraz 2021, S...","Love big, bold reds? Then you’ve likely heard ...",£9.99 per bottle,75CL,Shiraz,NaN,Screwcap,South Africa,10.9,"Black Fruit, Black Pepper, Black Plum, Blackbe...",per bottle,Red,ABV 14.50%,Western Cape,Bold & Spicy,2021,NaN,0.75
210,"Wynns Coonawarra Estate Shiraz 2020/21, Coonaw...",Coonawarra's cool climate and famous terra ros...,£14.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.8,"Black Plum, Blackberry, Blackcurrant, Blueberr...",per bottle,Red,ABV 14.40%,South East Australia,Bold & Spicy,2021,Coonawarra,0.75
238,Penfolds 'Koonunga Hill Seventy Six' Shiraz-Ca...,"When it comes to reds from Down Under, you can...",£16.99 per bottle,75CL,Shiraz,Cabernet Sauvignon,Screwcap,Australia,10.9,"Black Plum, Blackberry, Blackcurrant, Blueberr...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2021,NaN,0.75
268,"Jam Shed Shiraz 2021/22, Australia",Jam Shed was created with one thing in mind – ...,£8.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.1,"Jammy, Red Cherry, Red Plum, Vanilla",per bottle,Red,ABV 13.50%,NaN,Rich & Juicy,2022,NaN,0.75
361,"Penfolds 'Kalimna Bin 28' Shiraz 2019/20, Aust...",Kalimna Bin 28 was first produced in 1959 and ...,£34.99 per bottle,75CL,Shiraz,NaN,Natural Cork,Australia,10.9,"Vanilla, Black Pepper, Black Plum, Blackberry,...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2020,Barossa Valley,0.75
392,Penfolds 'Max's' Shiraz-Cabernet Sauvignon 201...,Penfolds is Australia's leading winery. The mu...,£22.99 per bottle,75CL,Shiraz,Cabernet Sauvignon,Natural Cork,Australia,10.9,"Vanilla, Black Plum, Blackberry, Blackcurrant,...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2019,NaN,0.75
421,"Grant Burge 'Fifth Generation' Shiraz 2018, Ba...","Fifth-generation winemaker, Grant Burge, is t...",£16.99 per bottle,75CL,Shiraz,"Grenache, Tempranillo",Screwcap,Australia,10.9,"Black Plum, Blackberry, Blueberry, Chocolate, ...",per bottle,Red,ABV 14.50%,Australia,Bold & Spicy,2018,Barossa Valley,0.75
453,"Smith & Wright Shiraz 2020/21, Australia",Smith & Wright is the creation of a duo with a...,£7.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.1,"Vanilla, Black Pepper, Raspberry, Red Cherry, ...",per bottle,Red,ABV 13.50%,South East Australia,Bold & Spicy,2021,NaN,0.75
465,"Two Hands 'Gnarly Dudes' Shiraz 2021/22, Baros...","21 years ago, Michael Twelftree and Richard Mi...",£21.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.8,"Vanilla, Black Pepper, Black Plum, Blackberry,...",per bottle,Red,ABV 14.40%,South Australia,Bold & Spicy,2022,Barossa Valley,0.75
470,Plum & Pepper Barossa Shiraz 2017,The key to Australian Shiraz is its intensity....,£14.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.9,"Black Pepper, Black Plum, Blackberry, Blackcur...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2017,Barossa Valley,0.75
498,"Torbreck 'Woodcutter's' Shiraz 2020/21, Barossa",Torbreck 'The Laird' Shiraz costs £660 per bot...,£23.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,11.3,"Vanilla, Black Cherry, Blackberry, Chocolate, ...",per bottle,Red,ABV 15.00%,South Australia,Bold & Spicy,2021,Barossa Valley,0.75
499,"Pringle Bay Shiraz 2022/23, Western Cape",The Pringle Bay range is a rarity – winemaking...,£9.99 per bottle,75CL,Shiraz,NaN,Screwcap,South Africa,10.5,"Black Cherry, Blackberry, Spice",per bottle,Red,ABV 14.00%,Western Cape,Rich & Juicy,2023,NaN,0.75
500,"Making Tracks Shiraz 2019/20, South Australia",Shiraz is Australia's star grape. This is bold...,£10.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.9,"Vanilla, Black Pepper, Blackberry, Blackcurran...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2020,NaN,0.75
534,"19 Crimes Red Blend, Australia","In 1788, 'punishment by transportation' to Aus...",£9.99 per bottle,75CL,Shiraz,"Cabernet Sauvignon, Merlot, Petit Syrah",Screwcap,Australia,10.5,"Black Plum, Blackcurrant, Vanilla",per bottle,Red,ABV 14.00%,South East Australia,Rich & Juicy,NV,NaN,0.75
587,Definition Barossa Shiraz 2019/20,The Definition range brings the world’s greate...,£13.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.5,"Black Pepper, Blackberry, Blackcurrant, Bluebe...",per bottle,Red,ABV 14.00%,South Australia,Bold & Spicy,2020,Barossa Valley,0.75
628,"Grant Burge 'Filsell' Shiraz 2017/19, Barossa","A deep, intense Shiraz from Grant Burge, this ...",£29.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.9,"Liquorice, Black Pepper, Black Plum, Blackberr...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2019,Barossa Valley,0.75
643,"Jim Barry 'McRae Wood' Shiraz 2013, Clare Valley",The late Jim Barry is a godfather of Australia...,£37.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.5,"Blackberry, Earth, Red Fruit, Vanilla",per bottle,Red,ABV 14.00%,South Australia,Bold & Spicy,2013,Clare Valley,0.75
673,"Mollydooker 'The Boxer' Shiraz 2020/21, Australia",The Boxer Shiraz is perhaps the lightest and m...,£29.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,12.0,"Vanilla, Black Cherry, Black Pepper, Black Plu...",per bottle,Red,ABV 16.00%,South Australia,Bold & Spicy,2020,Mclaren Vale,0.75
725,"Torbreck 'The Struie' Shiraz 2020/21, Barossa",Torbreck is one of the most celebrated produce...,£49.99 per bottle,75CL,Shiraz,NaN,Natural Cork,Australia,11.3,"Smoke, Black Cherry, Black Pepper, Black Plum,...",per bottle,Red,ABV 15.00%,South Australia,Bold & Spicy,2021,Barossa Valley,0.75
726,"Two Hands Ares Shiraz 2017/18, Barossa Valley",Deep garnet-purple in color and intensely scen...,£89.99 per bottle,75CL,Shiraz,NaN,Natural Cork,Australia,10.9,"Black Fruit, Black Pepper, Black Plum, Blackbe...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2018,Barossa Valley,0.75
727,"Two Hands 'Bella's Garden' Shiraz 2017/18, Bar...",Two Hands was started on a shoestring with two...,£39.99 per bottle,75CL,Shiraz,NaN,Natural Cork,Australia,11.3,"Mint, Black Cherry, Black Plum, Blackberry, Bl...",per bottle,Red,ABV 15.00%,South Australia,Bold & Spicy,2018,Barossa Valley,0.75
728,"Two Hands 'Lily's Garden' Shiraz 2018/19, McLa...",The Two Hands winery was formed by a duo of fr...,£39.99 per bottle,75CL,Shiraz,NaN,Natural Cork,Australia,11.3,"Vanilla, Black Cherry, Black Plum, Blackcurran...",per bottle,Red,ABV 15.00%,South Australia,Bold & Spicy,2019,Mclaren Vale,0.75
775,"Copper Kingdom Shiraz 2017, Barossa",Barossa is where you’ll find some of Australia...,£14.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.9,"Leather, Black Pepper, Blackberry, Blackcurran...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2017,Barossa Valley,0.75
779,"Penfolds Bin 8 Shiraz-Cabernet Sauvignon 2019,...",Penfolds are widely considered to be Australia...,£29.99 per bottle,75CL,Shiraz,Cabernet Sauvignon,Natural Cork,Australia,10.9,"Black Plum, Blackcurrant, Chocolate, Strawberr...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2019,NaN,0.75
961,"Penfolds Bin 2 Shiraz-Mataro 2019/20, South Au...",Penfolds’ Bin 2 was first released in 1960 – b...,£29.99 per bottle,75CL,Shiraz,Mataro,Natural Cork,Australia,10.9,"Black Plum, Blackcurrant, Chocolate, Dried Her...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2020,NaN,0.75
963,"Yellow Tail Shiraz 2020/21, Australia","In quintessential Aussie Shiraz style, Yellow ...",£7.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.1,"Vanilla, Black Fruit, Black Pepper, Black Plum...",per bottle,Red,ABV 13.50%,South East Australia,Bold & Spicy,2021,NaN,0.75
965,"Cape Mentelle Shiraz 2018, Margaret River",Cape Mentelle is one of Margaret River’s 'foun...,£32.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,11.3,"Black Cherry, Black Pepper, Blackcurrant, Liqu...",per bottle,Red,ABV 15.00%,NaN,Bold & Spicy,2018,NaN,0.75
1107,"Kangarilla Road Shiraz 2020/21, McLaren Vale","In 1997, the O’Brien family purchased an old v...",£14.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.9,"Vanilla, Black Cherry, Black Plum, Blackberry,...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2021,Mclaren Vale,0.75
1188,"Penfolds 'St Henri' Shiraz 2018, South Australia",Penfolds began in 1844 and is arguably Austral...,£100.00 per bottle,75CL,Shiraz,Cabernet Sauvignon,Natural Cork,Australia,10.9,"Black Cherry, Black Pepper, Blackberry, Chocol...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2018,NaN,0.75
1191,Peter Lehmann '8 Songs' Shiraz 2016,This release is part of Peter Lehmann's Master...,£25.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.9,NaN,per bottle,Red,ABV 14.50%,NaN,NaN,2016,Barossa Valley,0.75
1194,Peter Lehmann 'The Barossan' Shiraz 2019 Magnu...,"With rolling hills, hot, dry summers and some ...",£37.99 per bottle,1.5LTR,Shiraz,NaN,Screwcap,Australia,21.8,"Black Pepper, Black Plum, Blackberry, Blackcur...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2019,Barossa Valley,1.50
1195,"Peter Lehmann 'VSV' Shiraz 2016, Barossa",Peter Lehmann only make their coveted VSV rang...,£34.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.9,"Black Pepper, Black Plum, Blackberry, Vanilla",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2016,Barossa Valley,0.75
1211,"Reyneke 'Vinehugger' Organic Red 2019/20, West...",Reyneke believe there’s a lot to be said about...,£12.99 per bottle,75CL,Shiraz,Cabernet Sauvignon,Natural Cork,South Africa,10.5,"Red Fruit, Black Fruit, Black Pepper",per bottle,Red,ABV 14.00%,Western Cape,Smooth & Mellow,2020,NaN,0.75
1236,"Shaw + Smith Shiraz 2019, Australia",Shaw & Smith was founded in 1990 by Martin Sha...,£33.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,10.9,"White Pepper, Black Plum, Blackberry, Blackcur...",per bottle,Red,ABV 14.50%,South Australia,Bold & Spicy,2019,Adelaide Hills,0.75
1241,"St Hallett 'Old Block' Shiraz 2016, Barossa Va...","Led by winemaker Helen McCarthy, St Hallett dr...",£74.99 per bottle,75CL,Shiraz,NaN,Screwcap,Australia,11.0,"Liquorice, Black Pepper, Black Plum, Blackberr...",per bottle,Red,ABV 14.60%,South Australia,Bold & Spicy,2016,Barossa Valley,0.75
1264,Torbreck Descendant Shiraz 2012,Torbreck is one of Australia's leading winerie...,£120.00 per bottle,75CL,Shiraz,Viognier,Natural Cork,Australia,11.3,"Violet, Black Cherry, Black Plum, Blackberry, ...",per bottle,Red,ABV 15.00%,South Australia,Bold & Spicy,2012,Barossa Valley,0.75
1265,"Torbreck 'Runrig' Shiraz 2012/2014, Barossa Va...",Torbreck's Runrig Shiraz is blended with a das...,£180.00 per bottle,75CL,Shiraz,Viognier,Natural Cork,Australia,11.6,"White Pepper, Black Plum, Blackberry, Blackcur...",per bottle,Red,ABV 15.50%,South Australia,Bold & Spicy,2012,Barossa Valley,0.75
1271,"Two Hands 'Samantha's Garden' Shiraz 2018, Cla...",Two Hands' 'Garden' range are examples of Shir...,£40.00 per bottle,75CL,Shiraz,NaN,Natural Cork,Australia,11.6,"White Pepper, Black Fruit, Black Plum, Blackbe...",per bottle,Red,ABV 15.50%,South Australia,Bold & Spicy,2018,Clare Valley,0.75

In [11]:
df_wine.Region.value_counts()

Region
Burgundy           101
Bordeaux            67
Marlborough         65
Loire               59
South Australia     56
                  ...
Oregon               1
Coastal              1
Elgin                1
Bulgaria             1
Basilicata           1
Name: count, Length: 94, dtype: int64

## adapt

In [ ]:
# Here are some of possible binary attributes. You can always propose your own attributes.
titanic_bin = {
    'Survived': titanic_df['Survived'] == 1,
    'FirstClass': titanic_df['Pclass'] == 1,
    'French': titanic_df['Embarked'] == 'C',  # 'C' means 'Cherbourg'
    'Adult': titanic_df['Age'] >= 18,
    'Child': titanic_df['Age'] < 18,
    'Male': titanic_df['Sex'] == 'male',
    'Female': titanic_df['Sex'] == 'female',
}
titanic_bin = pd.DataFrame(titanic_bin)
titanic_bin.head()