In [43]:
import pandas as pd
import caspailleur as csp
import paspailleur as psp

# Binary analysis

In [46]:
df = pd.read_csv("../data/binarized/WineDatasetBIN.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1284 entries, 0 to 1283
Columns: 390 entries, Grape_Agiorgitiko to Style_nan
dtypes: bool(253), int64(137)
memory usage: 1.7 MB

## Concepts

In [53]:
new_concepts_df = csp.mine_concepts(
  df, min_support=100, min_delta_stability=20,
  to_compute=['intent', 'extent', 'keys', 'support', 'delta_stability', 'sub_concepts']
)

new_concepts_df.head(10)

,intent,extent,keys,support,delta_stability,sub_concepts
concept_id,,,,,,
0,{},"{414, 168, 830, 994, 859, 29, 776, 475, 960, 1...",[{}],1284,450,"{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
1,{Closure_Natural Cork},"{997, 168, 1113, 486, 348, 1226, 1171, 1118, 1...",[{Closure_Natural Cork}],834,416,"{134, 136, 137, 138, 9, 10, 14, 142, 144, 145,..."
2,{Vintage_bin_Vintage>2020},"{822, 168, 1214, 1171, 830, 1015, 859, 562, 52...",[{Vintage_bin_Vintage>2020}],591,268,"{138, 139, 140, 17, 18, 21, 23, 25, 153, 156, ..."
3,{Type_White},"{822, 1113, 1171, 1015, 994, 1061, 859, 33, 31...",[{Type_White}],584,251,"{129, 138, 141, 14, 144, 17, 146, 153, 154, 15..."
4,{Type_Red},"{414, 168, 348, 1226, 1118, 177, 29, 480, 409,...",[{Type_Red}],565,150,"{131, 136, 137, 10, 19, 22, 152, 155, 156, 31,..."
5,{Price_bin_15<Price<=25},"{822, 625, 168, 830, 177, 29, 615, 235, 394, 1...",[{Price_bin_15<Price<=25}],515,192,"{143, 145, 18, 20, 162, 34, 164, 37, 39, 171, ..."
6,{Country_France},"{822, 997, 1214, 1226, 1061, 994, 177, 33, 314...",[{Country_France}],502,84,"{129, 9, 139, 143, 149, 150, 29, 40, 169, 171,..."
7,{ABV_bin_12.5<ABV<=13.5},"{414, 822, 1226, 1015, 994, 1061, 859, 562, 77...",[{ABV_bin_12.5<ABV<=13.5}],482,180,"{132, 136, 139, 141, 145, 146, 21, 26, 30, 164..."
8,{Vintage_bin_2015<Vintage<=2020},"{414, 1113, 348, 1226, 1118, 994, 177, 29, 409...",[{Vintage_bin_2015<Vintage<=2020}],431,108,"{159, 100, 198, 102, 104, 44, 174, 16, 82, 19,..."
9,"{Country_France, Closure_Natural Cork}","{997, 1226, 1061, 994, 177, 33, 314, 1024, 562...","[{Country_France, Closure_Natural Cork}]",418,208,"{196, 101, 104, 107, 46, 143, 81, 115, 122, 91..."

In [55]:
new_concepts_df.to_csv("../results/WineDatasetConcepts.csv", index=False)

## Implications

In [57]:
implications_df = csp.mine_implications(
  df, basis_name='Canonical', unit_base=True,
  to_compute=['premise', 'conclusion', 'extent', 'support', 'delta_stability'],
  min_support=30,
  min_delta_stability=20,
)

implications_df.head(20)

,premise,conclusion,extent,support,delta_stability
implication_id,,,,,
0,{Style_Mellow},Type_Red,"{554, 87, 64, 455, 804, 325, 874, 330, 744, 78...",59,21
1,{Style_Mellow},Style_Smooth,"{554, 87, 64, 455, 804, 325, 874, 330, 744, 78...",59,21
2,{Style_Juicy},Type_Red,"{414, 268, 1157, 888, 348, 534, 613, 658, 0, 1...",65,22
3,{Style_Juicy},Style_Rich,"{414, 268, 1157, 888, 348, 534, 613, 658, 0, 1...",65,22
4,{Style_Bold},Type_Red,"{116, 78, 417, 149, 959, 629, 464, 410, 669, 6...",113,34
5,{Style_Bold},Style_Spicy,"{116, 78, 417, 149, 959, 629, 464, 410, 669, 6...",113,34
6,{Style_Spicy},Type_Red,"{116, 78, 417, 149, 959, 629, 464, 410, 669, 6...",113,34
7,{Style_Spicy},Style_Bold,"{116, 78, 417, 149, 959, 629, 464, 410, 669, 6...",113,34
8,"{Style_Rounded, Vintage_bin_Vintage>2020}",Type_White,"{635, 1053, 174, 44, 673, 273, 57, 704, 183, 7...",61,23
9,"{Style_Rounded, Vintage_bin_Vintage>2020}",Style_Ripe,"{635, 1053, 174, 44, 673, 273, 57, 704, 183, 7...",61,23
10,"{Style_Full Bodied, Closure_Natural Cork}",Type_Red,"{1047, 168, 1225, 1085, 366, 1118, 1108, 177, ...",140,43
11,"{Style_Full Bodied, Closure_Natural Cork}",Style_Savoury,"{1047, 168, 1225, 1085, 366, 1118, 1108, 177, ...",140,43
12,"{Style_Savoury, Closure_Natural Cork}",Type_Red,"{1047, 168, 1225, 1085, 366, 1118, 1108, 177, ...",140,43
13,"{Style_Savoury, Closure_Natural Cork}",Style_Full Bodied,"{1047, 168, 1225, 1085, 366, 1118, 1108, 177, ...",140,43
14,"{Grape_Pinot Noir, Style_Elegant}",Type_Red,"{590, 1052, 1095, 971, 1172, 1226, 616, 403, 7...",72,34
15,"{Grape_Pinot Noir, Style_Elegant}",Style_Light,"{590, 1052, 1095, 971, 1172, 1226, 616, 403, 7...",72,34
16,"{Grape_Pinot Noir, Style_Light}",Type_Red,"{590, 1052, 1095, 971, 1172, 1226, 616, 403, 7...",72,34
17,"{Grape_Pinot Noir, Style_Light}",Style_Elegant,"{590, 1052, 1095, 971, 1172, 1226, 616, 403, 7...",72,34
18,"{Type_White, Style_Rounded}",Style_Ripe,"{673, 57, 1171, 796, 574, 994, 863, 111, 3, 98...",90,29
19,"{Type_White, Style_Rich}",Style_Toasty,"{1113, 909, 1015, 1, 33, 338, 314, 1024, 375, ...",138,23

In [58]:
implications_df.to_csv("../results/WineDatasetImplications.csv", index=False)

# Paspailleur analysis

In [59]:
df = pd.read_csv("../data/preprocessed/WineDatasetPAS.csv")
df.head()

,Title,Price,Grape,Closure,Country,Characteristics,Type,ABV,Region,Style,Vintage,Price_bin,ABV_bin,Vintage_bin
0,"The Guv'nor, Spain",13.320000,Tempranillo,Natural Cork,Spain,"{'Blackberry', 'Blackcurrant', 'Vanilla'}",Red,14.0,NaN,"{'Rich', 'Juicy'}",NaN,Price<=15,13.5<ABV<=14.5,NaN
1,Bread & Butter 'Winemaker's Selection' Chardon...,21.320000,Chardonnay,Natural Cork,USA,"{'Green Apple', 'Vanilla', 'Pineapple', 'Stone...",White,13.5,California,"{'Rich', 'Toasty'}",2021.0,15<Price<=25,12.5<ABV<=13.5,Vintage>2020
2,"Oyster Bay Sauvignon Blanc 2022, Marlborough",16.653333,Sauvignon Blanc,Screwcap,New Zealand,"{'Green Apple', 'Lemon', 'Grapefruit', 'Grass'...",White,13.0,Marlborough,"{'Zesty', 'Crisp'}",2022.0,15<Price<=25,12.5<ABV<=13.5,Vintage>2020
3,Louis Latour Mâcon-Lugny 2021/22,23.986667,Chardonnay,Natural Cork,France,"{'Lemon', 'Peach', 'Floral', 'Apricot'}",White,13.5,Burgundy,"{'Ripe', 'Rounded'}",2022.0,15<Price<=25,12.5<ABV<=13.5,Vintage>2020
4,Bread & Butter 'Winemaker's Selection' Pinot N...,21.320000,Pinot Noir,Natural Cork,USA,"{'Smoke', 'Cedar', 'Raspberry', 'Red Fruit', '...",Red,13.5,California,"{'Smooth', 'Mellow'}",2021.0,15<Price<=25,12.5<ABV<=13.5,Vintage>2020

In [60]:
df.drop(columns=["Price_bin", "ABV_bin", "Vintage_bin", "Title"], inplace=True)

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1284 entries, 0 to 1283
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Price            1284 non-null   float64
 1   Grape            1275 non-null   str
 2   Closure          1279 non-null   str
 3   Country          1284 non-null   str
 4   Characteristics  1284 non-null   str
 5   Type             1279 non-null   str
 6   ABV              1281 non-null   float64
 7   Region           1124 non-null   str
 8   Style            1284 non-null   str
 9   Vintage          1100 non-null   float64
dtypes: float64(3), str(7)
memory usage: 100.4 KB

In [67]:
CharacteristicsPattern = psp.pattern_factory(psp.bip.ItemSetPattern)
StylePattern = psp.pattern_factory(psp.bip.ItemSetPattern)

PricePattern = psp.pattern_factory(
    psp.bip.ClosedIntervalPattern,
    BoundsUniverse=(
        0, 15, 25, 50, 1000
    )
)
ABVPattern = psp.pattern_factory(
    psp.bip.ClosedIntervalPattern,
    BoundsUniverse=(
        0, 12.5, 13.5, 14.5, 50
    )
)
VintagePattern = psp.pattern_factory(
    psp.bip.ClosedIntervalPattern,
    BoundsUniverse=(
        0, 2015, 2020, 2030
    )
)


GrapePattern = psp.pattern_factory(psp.bip.CategorySetPattern, Universe=set(df["Grape"].dropna().unique()))
ClosurePattern = psp.pattern_factory(psp.bip.CategorySetPattern, Universe=set(df["Closure"].dropna().unique()))
CountryPattern = psp.pattern_factory(psp.bip.CategorySetPattern, Universe=set(df["Country"].dropna().unique()))
TypePattern = psp.pattern_factory(psp.bip.CategorySetPattern, Universe=set(df["Type"].dropna().unique()))
RegionPattern = psp.pattern_factory(psp.bip.CategorySetPattern, Universe=set(df["Region"].dropna().unique()))

In [68]:
class WinePattern(psp.bip.CartesianPattern):
    DimensionTypes = {
        'Price': PricePattern,
        'Grape': GrapePattern,
        'Closure': ClosurePattern,
        'Country': CountryPattern,
        'Characteristics': CharacteristicsPattern,
        'Type': TypePattern,
        'ABV': ABVPattern,
        'Region': RegionPattern,
        'Style': StylePattern,
        'Vintage': VintagePattern,
    }

In [69]:
df = df[['Price', 'Grape', 'Closure', 'Country', 'Characteristics', 'Type', 'ABV', 'Region', 'Style', 'Vintage']]

In [70]:
for f in df.columns:
    if df[f].isna().any():
        p = WinePattern.DimensionTypes[f].get_min_pattern()
        df[f] = df[f].fillna(p)
        print(f"Found NaN values in dimension {f}. Replace them by pattern: {p}")

In [71]:
ps = psp.PatternStructure(WinePattern)
ps.fit(df.to_dict('index'), min_atom_support=0.1, use_tqdm=True)
print('#objects x #atomic_patterns', ps.shape)

Compute atomic extents:   0%|          | 0/1200 [00:00<?, ?it/s]
Compute atomic extents:   2%|▎         | 30/1200 [00:00<00:03, 292.65it/s]
Compute atomic extents:   5%|▌         | 60/1200 [00:00<00:04, 255.02it/s]
Compute atomic extents:   8%|▊         | 90/1200 [00:00<00:04, 270.03it/s]
Compute atomic extents:  10%|█         | 120/1200 [00:00<00:04, 265.24it/s]
Compute atomic extents:  12%|█▏        | 147/1200 [00:00<00:04, 261.21it/s]
Compute atomic extents:  14%|█▍        | 174/1200 [00:00<00:03, 263.12it/s]
Compute atomic extents:  17%|█▋        | 201/1200 [00:00<00:03, 252.05it/s]
Compute atomic extents:  19%|█▉        | 230/1200 [00:00<00:03, 261.05it/s]
Compute atomic extents:  22%|██▏       | 261/1200 [00:00<00:03, 273.69it/s]
Compute atomic extents:  24%|██▍       | 290/1200 [00:01<00:03, 277.83it/s]
Compute atomic extents:  26%|██▋       | 318/1200 [00:01<00:03, 268.90it/s]
Compute atomic extents:  29%|██▉       | 346/1200 [00:01<00:03, 265.59it/s]
Compute atomic extents:  31%|███       | 373/1200 [00:01<00:03, 256.18it/s]
Compute atomic extents:  33%|███▎      | 399/1200 [00:01<00:03, 234.36it/s]
Compute atomic extents:  35%|███▌      | 423/1200 [00:01<00:03, 234.59it/s]
Compute atomic extents:  37%|███▋      | 448/1200 [00:01<00:03, 237.80it/s]
Compute atomic extents:  39%|███▉      | 472/1200 [00:01<00:03, 216.01it/s]
Compute atomic extents:  41%|████▏     | 497/1200 [00:01<00:03, 223.73it/s]
Compute atomic extents:  44%|████▎     | 524/1200 [00:02<00:02, 235.51it/s]
Compute atomic extents:  46%|████▌     | 552/1200 [00:02<00:02, 245.73it/s]
Compute atomic extents:  48%|████▊     | 577/1200 [00:02<00:02, 243.90it/s]
Compute atomic extents:  50%|█████     | 602/1200 [00:02<00:02, 239.94it/s]
Compute atomic extents:  52%|█████▏    | 627/1200 [00:02<00:02, 231.89it/s]
Compute atomic extents:  54%|█████▍    | 651/1200 [00:02<00:02, 227.51it/s]
Compute atomic extents:  56%|█████▋    | 678/1200 [00:02<00:02, 238.33it/s]
Compute atomic extents:  59%|█████▊    | 704/1200 [00:02<00:02, 243.22it/s]
Compute atomic extents:  61%|██████    | 729/1200 [00:02<00:01, 236.75it/s]
Compute atomic extents:  63%|██████▎   | 760/1200 [00:03<00:01, 254.96it/s]
Compute atomic extents:  66%|██████▌   | 787/1200 [00:03<00:01, 257.23it/s]
Compute atomic extents:  68%|██████▊   | 813/1200 [00:03<00:01, 253.26it/s]
Compute atomic extents:  70%|███████   | 843/1200 [00:03<00:01, 266.69it/s]
Compute atomic extents:  73%|███████▎  | 878/1200 [00:03<00:01, 284.86it/s]
Compute atomic extents:  76%|███████▌  | 909/1200 [00:03<00:01, 288.47it/s]
Compute atomic extents:  78%|███████▊  | 942/1200 [00:03<00:00, 298.94it/s]
Compute atomic extents:  81%|████████  | 972/1200 [00:03<00:00, 292.59it/s]
Compute atomic extents:  84%|████████▎ | 1002/1200 [00:03<00:00, 276.72it/s]
Compute atomic extents:  86%|████████▌ | 1030/1200 [00:04<00:00, 273.01it/s]
Compute atomic extents:  88%|████████▊ | 1058/1200 [00:04<00:00, 270.39it/s]
Compute atomic extents:  90%|█████████ | 1086/1200 [00:04<00:00, 261.72it/s]
Compute atomic extents:  93%|█████████▎| 1119/1200 [00:04<00:00, 277.98it/s]
Compute atomic extents:  96%|█████████▌| 1147/1200 [00:04<00:00, 265.13it/s]
Compute atomic extents:  98%|█████████▊| 1174/1200 [00:04<00:00, 248.96it/s]
Compute atomic extents: 100%|██████████| 1200/1200 [00:04<00:00, 255.76it/s]

Compute order of patterns: 100%|██████████| 289/289 [00:00<00:00, 17953.85it/s]

#objects x #atomic_patterns (1284, 289)

In [72]:
concepts = ps.mine_concepts(min_delta_stability=30, min_support=500, algorithm='gSofia', use_tqdm=True)

gSofia algorithm:   0%|          | 0/289 [00:00<?, ?it/s]
gSofia algorithm:  97%|█████████▋| 280/289 [00:00<00:00, 1014.04it/s]

Compute intents:   0%|          | 0/398 [00:00<?, ?it/s]
Compute intents:   6%|▌         | 23/398 [00:00<00:01, 220.93it/s]
Compute intents:  12%|█▏        | 47/398 [00:00<00:01, 225.70it/s]
Compute intents:  18%|█▊        | 70/398 [00:00<00:01, 221.33it/s]
Compute intents:  24%|██▍       | 95/398 [00:00<00:01, 228.04it/s]
Compute intents:  30%|██▉       | 118/398 [00:00<00:01, 219.68it/s]
Compute intents:  35%|███▌      | 141/398 [00:00<00:01, 219.79it/s]
Compute intents:  41%|████      | 164/398 [00:00<00:01, 219.35it/s]
Compute intents:  47%|████▋     | 186/398 [00:00<00:01, 183.45it/s]
Compute intents:  53%|█████▎    | 212/398 [00:01<00:00, 202.03it/s]
Compute intents:  59%|█████▉    | 234/398 [00:01<00:00, 203.16it/s]
Compute intents:  64%|██████▍   | 255/398 [00:01<00:00, 202.24it/s]
Compute intents:  69%|██████▉   | 276/398 [00:01<00:00, 187.55it/s]
Compute intents:  75%|███████▍  | 297/398 [00:01<00:00, 193.19it/s]
Compute intents:  80%|████████  | 320/398 [00:01<00:00, 200.43it/s]
Compute intents:  87%|████████▋ | 345/398 [00:01<00:00, 208.81it/s]
Compute intents:  92%|█████████▏| 367/398 [00:01<00:00, 199.00it/s]
Compute intents: 100%|██████████| 398/398 [00:01<00:00, 204.15it/s]

In [73]:
print(f"# concepts: {len(concepts):,}")
extent, intent = concepts[50]
print("Concept #50")
print(f"* objects in the concept: {list(extent)[:10]} (some of them)")
print(f"* pattern of the concept: {intent}")

# concepts: 398
Concept #50
* objects in the concept: [1, 2, 3, 4, 5, 10, 11, 14, 16, 17] (some of them)
* pattern of the concept: {'ABV': [0.0, 14.5], 'Closure': {'Screwcap', 'Natural Cork'}, 'Country': {'France', 'USA', 'New Zealand', 'Argentina', 'Australia', 'South Africa', 'Chile'}, 'Grape': {'Sauvignon Blanc', 'Chardonnay', 'Malbec', 'Merlot', 'Cabernet Sauvignon', 'Pinot Noir', 'Grenache'}, 'Price': [0.0, 1000.0], 'Region': NOT({{'Mendoza', 'Valencia And Murcia', 'Dao', 'Australia', 'Douro', 'Romania', 'Hawkes Bay', 'Sardinia', 'Georgia', 'Bourgogne', 'Vinho Verde', 'Limoux', 'Usa', 'Rhône', 'Rioja And Navarra', 'Serbia', 'Trentino Alto Adige', 'Loire', 'Languedoc-Roussillon', 'Oregon', 'Sicily', 'Burgundy', 'Lisboa', 'South Australia', 'Tuscany', 'South East Australia', 'La Rioja', 'Veneto', 'Moldova', 'Lebanon', 'Nelson', 'Alentejo', 'Western Australia', 'Swartland', 'Hampshire', 'North', 'Greece', 'Península De Setúbal', 'Catalunya', 'New South Wales', 'Stellenbosch', 'Dordogne', 'Coastal', 'Hungary', 'Provence', 'Castilla-La Mancha', 'Prosecco Doc', 'Puglia', 'Elgin', 'Other France', 'Chile', 'Sw France (Ec. Boredeaux)', 'Franschhoek', 'Tasmania', 'Western Cape', 'Corsica', 'Surrey', 'California', 'Sussex', 'Basilicata', 'Abruzzo', 'Gisborne', 'Constantia', 'Kvareli', 'Waipara', 'Castilla Y León', 'Piedmont', 'Galicia', 'Le Marche', 'Victoria', 'Aragon', 'Aconcagua', 'Italy', 'Prosecco Docg', 'Robertson', 'Tejo', 'Austria', 'Martinborough', 'Central Valley', 'Bordeaux', 'Alsace', 'Slovenia', 'Kent', 'Bulgaria', 'Campania', 'San Juan', 'Marlborough', 'Lombardy', 'Central Otago', 'Germany', 'Beaujolais', 'Walker Bay', 'Jura & Savoie', 'Washington State'}}), 'Type': {'White', 'Red', 'Rosé'}}

In [76]:
implications = ps.mine_implications(
    min_delta_stability=30, min_support=500, max_key_length=4,
    algorithm='gSofia',
    reduce_conclusions=True, use_tqdm=True
)
print(len(implications))

gSofia algorithm:   0%|          | 0/289 [00:00<?, ?it/s]
gSofia algorithm:  97%|█████████▋| 280/289 [00:00<00:00, 1080.60it/s]

Compute intents:   0%|          | 0/398 [00:00<?, ?it/s]
Compute intents:   6%|▌         | 22/398 [00:00<00:01, 216.44it/s]
Compute intents:  12%|█▏        | 46/398 [00:00<00:01, 229.08it/s]
Compute intents:  17%|█▋        | 69/398 [00:00<00:01, 210.99it/s]
Compute intents:  23%|██▎       | 93/398 [00:00<00:01, 220.02it/s]
Compute intents:  29%|██▉       | 117/398 [00:00<00:01, 225.60it/s]
Compute intents:  36%|███▌      | 142/398 [00:00<00:01, 232.19it/s]
Compute intents:  42%|████▏     | 166/398 [00:00<00:01, 225.48it/s]
Compute intents:  47%|████▋     | 189/398 [00:00<00:00, 224.47it/s]
Compute intents:  54%|█████▍    | 215/398 [00:00<00:00, 229.29it/s]
Compute intents:  60%|█████▉    | 238/398 [00:01<00:00, 226.70it/s]
Compute intents:  66%|██████▌   | 261/398 [00:01<00:00, 218.95it/s]
Compute intents:  72%|███████▏  | 285/398 [00:01<00:00, 222.68it/s]
Compute intents:  77%|███████▋  | 308/398 [00:01<00:00, 214.33it/s]
Compute intents:  83%|████████▎ | 330/398 [00:01<00:00, 203.66it/s]
Compute intents:  89%|████████▉ | 356/398 [00:01<00:00, 217.69it/s]
Compute intents: 100%|██████████| 398/398 [00:01<00:00, 218.49it/s]

Mine premise candidates: 0it [00:00, ?it/s]
Mine premise candidates: 1it [13:54, 834.08s/it][A

Construct implications: 100%|██████████| 1/1 [00:00<00:00, 111.91it/s]

1

In [77]:
implications

OrderedDict([({},
              {'Closure': NOT({{'Vinolok', 'Screwcap', 'Natural Cork', 'Synthetic Cork'}}), 'Grape': NOT({{'Aglianico', 'Pinotage', 'Primitivo', 'Colombard', 'Gewürztraminer', 'Pais', 'Gamay', 'Mourvèdre', 'Viura', 'Torrontes', 'Pecorino', 'Corvina', 'Loureiro', 'Malbec', 'Grillo', 'Vespaiola', 'Pinot Blanc', 'Rolle', 'Marsanne', 'Verdejo', 'Godello', 'Pinot Noir', 'Vermentino', 'Bacchus', 'Nerello Mascalese', 'Sangiovese', 'Sauvignon Blanc', 'Nerello', 'Pinot Gris', 'Chenin Blanc', 'Falanghina', 'Grolleau', 'Albarino', 'Rkatsiteli', 'Cortese', 'Malagousia', 'Fernão Pires', 'Garnacha', 'Roussanne', 'Mencia', 'Gruner Veltliner', 'Glera', 'Muscat', 'Niellucciu', 'Carignan', 'Melon De Bourgogne', 'Xarel-Lo', 'Alicante Bouschet', 'Furmint', 'Zinfandel', 'Grenache Blanc', 'Pedro Ximénez', 'Castelão ', 'Shiraz', 'Tinta Barroca', 'Fiano', 'Non Varietal', 'Pinot Grigio', 'Garganega', 'Jacquere', 'Montepulciano', 'Syrah', 'Huxelrebe', 'Monastrell', 'Carménère', 'Negroamaro', 'Cabernet Franc', 'Picpoul', 'Mauzac', 'Greco', 'Sémillon', 'Merlot', 'Dolcetto', 'Cinsault', 'Pinot Meunier', 'Viognier', 'Black Muscat', 'Feteasca Alba', 'Touriga Nacional', 'Tinta Roriz', 'Turbiana', 'Rara Neagra', 'Chardonnay', 'Siegerrebe', 'Touriga Franca', 'Verdicchio', 'Syrah-Shiraz', 'Moscato', 'Trincadeira', "Nero D'Avola", 'Assyrtiko', 'Zwieigelt', 'Barbera', 'Malvasia', 'Cabernet Sauvignon', 'Alvarinho', 'Aligoté', 'Arinto', 'Inzolia', 'Nebbiolo', 'Rondinella', 'Agiorgitiko', 'Tempranillo', 'Saperavi', 'Airen', 'Grenache', 'Tibouren', 'Lambrusco Grasparossa', 'Riesling', 'Palomino', 'Sauvignon Gris', 'Xinomavro', 'Macabeo'}}), 'Price': [0.0, 1000.0], 'Region': NOT({{'Mendoza', 'Valencia And Murcia', 'Dao', 'Australia', 'Douro', 'Romania', 'Hawkes Bay', 'Sardinia', 'Georgia', 'Bourgogne', 'Vinho Verde', 'Limoux', 'Usa', 'Rhône', 'Rioja And Navarra', 'Serbia', 'Trentino Alto Adige', 'Loire', 'Languedoc-Roussillon', 'Oregon', 'Sicily', 'Burgundy', 'Lisboa', 'South Australia', 'Tuscany', 'South East Australia', 'La Rioja', 'Veneto', 'Moldova', 'Lebanon', 'Nelson', 'Alentejo', 'Western Australia', 'Swartland', 'Hampshire', 'North', 'Greece', 'Península De Setúbal', 'Catalunya', 'New South Wales', 'Stellenbosch', 'Dordogne', 'Coastal', 'Hungary', 'Provence', 'Castilla-La Mancha', 'Prosecco Doc', 'Puglia', 'Elgin', 'Other France', 'Chile', 'Sw France (Ec. Boredeaux)', 'Franschhoek', 'Tasmania', 'Western Cape', 'Corsica', 'Surrey', 'California', 'Sussex', 'Basilicata', 'Abruzzo', 'Gisborne', 'Constantia', 'Kvareli', 'Waipara', 'Castilla Y León', 'Piedmont', 'Galicia', 'Le Marche', 'Victoria', 'Aragon', 'Aconcagua', 'Italy', 'Prosecco Docg', 'Robertson', 'Tejo', 'Austria', 'Martinborough', 'Central Valley', 'Bordeaux', 'Alsace', 'Slovenia', 'Kent', 'Bulgaria', 'Campania', 'San Juan', 'Marlborough', 'Lombardy', 'Central Otago', 'Germany', 'Beaujolais', 'Walker Bay', 'Jura & Savoie', 'Washington State'}}), 'Type': NOT({{'Tawny', 'White', 'Brown', 'Red', 'Orange', 'Rosé'}})})])

## Subgroups

### Cheap white wine

In [168]:
df = pd.read_csv("../data/preprocessed/WineDatasetPAS.csv")
df.drop(columns=["Price_bin", "ABV_bin", "Vintage_bin", "Title"], inplace=True)
df = df[['Price', 'Grape', 'Closure', 'Country', 'Characteristics', 'Type', 'ABV', 'Region', 'Style', 'Vintage']]

In [169]:
df.head()

,Price,Grape,Closure,Country,Characteristics,Type,ABV,Region,Style,Vintage
0,13.320000,Tempranillo,Natural Cork,Spain,"{'Blackberry', 'Blackcurrant', 'Vanilla'}",Red,14.0,NaN,"{'Rich', 'Juicy'}",NaN
1,21.320000,Chardonnay,Natural Cork,USA,"{'Green Apple', 'Vanilla', 'Pineapple', 'Stone...",White,13.5,California,"{'Rich', 'Toasty'}",2021.0
2,16.653333,Sauvignon Blanc,Screwcap,New Zealand,"{'Green Apple', 'Lemon', 'Grapefruit', 'Grass'...",White,13.0,Marlborough,"{'Zesty', 'Crisp'}",2022.0
3,23.986667,Chardonnay,Natural Cork,France,"{'Lemon', 'Peach', 'Floral', 'Apricot'}",White,13.5,Burgundy,"{'Ripe', 'Rounded'}",2022.0
4,21.320000,Pinot Noir,Natural Cork,USA,"{'Smoke', 'Cedar', 'Raspberry', 'Red Fruit', '...",Red,13.5,California,"{'Smooth', 'Mellow'}",2021.0

In [176]:
goal_objects = set(
    df[(df['Type'] == 'Red') & (df['Characteristics'].apply(lambda s: 'Red Cherry' in s or 'Cedar' in s))].index
)
subgroups_iterator = ps.iter_subgroups(
    goal_objects=goal_objects,
    quality_measure='Precision', quality_threshold=0.65,
    max_length=2,
    use_tqdm=True
)

In [177]:
subgroups = list(subgroups_iterator)
print(len(subgroups))

Iterate subgroup candidates: 0.00it [00:00, ?it/s]

Iterate subgroup candidates: 40.4kit [00:00, 306kit/s]

9

In [178]:
subgroups

[SubgroupData(pattern={'Characteristics': {'Vanilla', 'Raspberry'}}, extent={449, 66, 611, 668, 584, 1101, 1261, 626, 1238, 380, 409, 444}, quality_value=0.8333333333333334, quality_name='Precision'),
 SubgroupData(pattern={'Characteristics': {'Vanilla', 'Strawberry'}}, extent={1156, 773, 421, 584, 748, 1238, 668}, quality_value=0.7142857142857143, quality_name='Precision'),
 SubgroupData(pattern={'Characteristics': {'Strawberry', 'Blackberry'}}, extent={1270, 717, 1246}, quality_value=0.6666666666666666, quality_name='Precision'),
 SubgroupData(pattern={'Characteristics': {'Raspberry'}, 'Style': {'Savoury'}}, extent={1168, 150}, quality_value=1.0, quality_name='Precision'),
 SubgroupData(pattern={'Characteristics': {'Strawberry'}, 'Style': {'Savoury'}}, extent={1156, 150}, quality_value=1.0, quality_name='Precision'),
 SubgroupData(pattern={'Characteristics': {'Raspberry'}, 'Style': {'Full Bodied'}}, extent={1168, 150}, quality_value=1.0, quality_name='Precision'),
 SubgroupData(pattern={'Characteristics': {'Strawberry'}, 'Style': {'Full Bodied'}}, extent={1156, 150}, quality_value=1.0, quality_name='Precision'),
 SubgroupData(pattern={'Characteristics': {'Strawberry', 'Black Fruit'}}, extent={1246}, quality_value=1.0, quality_name='Precision'),
 SubgroupData(pattern={'Characteristics': {'Vanilla'}, 'Style': {'Light'}}, extent={66, 421, 409, 748, 1261, 626, 1172, 1077, 1238, 281}, quality_value=0.7, quality_name='Precision')]

In [180]:
# Order subgroups 1) by simplicity of pattern, 2) by their quality
subgroups = sorted(subgroups, key=lambda sg_data: (len(sg_data.pattern), -sg_data.quality_value))
print("Subgroups of Red Whine with either Red Cherry or Cedar Characteristic:")
for pattern, objects, quality, quality_name in subgroups:
    print(f"Pattern: {pattern}")
    print(f"{quality_name}: {quality:.2%}, Support: {len(objects)} ({ps.measure_frequency(pattern):.0%} of data)")
    print()

Subgroups of Red Whine with either Red Cherry or Cedar Characteristic:
Pattern: {'Characteristics': {'Raspberry'}, 'Style': {'Savoury'}}
Precision: 100.00%, Support: 2 (0% of data)

Pattern: {'Characteristics': {'Strawberry'}, 'Style': {'Savoury'}}
Precision: 100.00%, Support: 2 (0% of data)

Pattern: {'Characteristics': {'Raspberry'}, 'Style': {'Full Bodied'}}
Precision: 100.00%, Support: 2 (0% of data)

Pattern: {'Characteristics': {'Strawberry'}, 'Style': {'Full Bodied'}}
Precision: 100.00%, Support: 2 (0% of data)

Pattern: {'Characteristics': {'Strawberry', 'Black Fruit'}}
Precision: 100.00%, Support: 1 (0% of data)

Pattern: {'Characteristics': {'Vanilla', 'Raspberry'}}
Precision: 83.33%, Support: 12 (1% of data)

Pattern: {'Characteristics': {'Vanilla', 'Strawberry'}}
Precision: 71.43%, Support: 7 (1% of data)

Pattern: {'Characteristics': {'Vanilla'}, 'Style': {'Light'}}
Precision: 70.00%, Support: 10 (1% of data)

Pattern: {'Characteristics': {'Strawberry', 'Blackberry'}}
Precision: 66.67%, Support: 3 (0% of data)

In [154]:
df[df['ABV'] >= 20]

,Price,Grape,Closure,Country,Characteristics,Type,ABV,Region,Style,Vintage
7,114.285714,NaN,Natural Cork,Scotland,{'nan'},Brown,40.0,NaN,{'nan'},NaN
471,27.980000,Touriga Nacional,Natural Cork,Portugal,"{'Jammy', 'Cigar Box', 'Cedar'}",Red,20.0,Douro,{'nan'},2018.0
472,22.653333,Touriga Nacional,Natural Cork,Portugal,"{'Nutmeg', 'Cinnamon', 'Almond'}",Tawny,20.0,Douro,{'nan'},NaN
474,49.320000,Tinta Barroca,Natural Cork,Portugal,"{'Jammy', 'Date', 'Prune'}",Red,20.5,Douro,{'nan'},2013.0
485,43.986667,Touriga Nacional,Natural Cork,Portugal,{'nan'},Red,20.5,Douro,{'nan'},2008.0
486,33.320000,Touriga Franca,Natural Cork,Portugal,"{'Caramel', 'Jammy', 'Fig'}",Tawny,20.0,Douro,{'nan'},NaN
663,71.973333,Palomino,Natural Cork,Spain,"{'Sweet Spice', 'Fig', 'Black Cherry', 'Raisin'}",White,20.5,NaN,{'nan'},NaN
708,39.986667,Touriga Nacional,Natural Cork,Portugal,"{'Walnut', 'Red Plum', 'Raisin', 'Fig', 'Toffe...",Tawny,20.0,Douro,{'nan'},NaN
854,47.142857,NaN,Natural Cork,Mexico,{'nan'},White,40.0,NaN,{'nan'},NaN
948,46.653333,Tinta Barroca,Natural Cork,Portugal,"{'Black Plum', 'Date', 'Prune'}",Red,20.5,Douro,{'nan'},2008.0
953,21.320000,Touriga Franca,Natural Cork,Portugal,"{'Blackcurrant', 'Raisin', 'Prune'}",Red,20.0,Douro,{'nan'},NaN
964,27.980000,Malvasia,Natural Cork,Portugal,"{'Lime', 'Peach', 'Honey'}",White,20.0,Douro,{'nan'},NaN
998,45.980000,Malvasia,Natural Cork,Portugal,"{'Caramel', 'Walnut', 'Raisin'}",White,20.0,NaN,{'nan'},NaN
1014,71.973333,Palomino,Natural Cork,Spain,"{'Caramel', 'Fig', 'Dried Fruit'}",White,20.0,NaN,{'nan'},NaN
1081,31.980000,Touriga Nacional,Natural Cork,Portugal,"{'Blackcurrant', 'Raisin', 'Prune'}",Red,20.0,Douro,{'nan'},NaN
1178,19.986667,Palomino,Natural Cork,Spain,"{'Toffee', 'Orange', 'Vanilla'}",White,20.0,NaN,{'nan'},NaN
1179,23.986667,Palomino,Natural Cork,Spain,"{'Walnut', 'Almond', 'Vanilla'}",White,20.0,NaN,{'nan'},NaN
1243,39.986667,Touriga Nacional,Natural Cork,Portugal,"{'Cedar', 'Fig', 'Black Plum', 'Leather'}",Tawny,20.0,Douro,{'nan'},NaN
1244,113.333333,Tinta Barroca,Natural Cork,Portugal,"{'Jammy', 'Chocolate', 'Dried Fruit'}",Red,20.0,Douro,{'nan'},2007.0

In [128]:
df[df['Type'] == 'Tawny']

,Price,Grape,Closure,Country,Characteristics,Type,ABV,Region,Style,Vintage
472,22.653333,Touriga Nacional,Natural Cork,Portugal,"{'Nutmeg', 'Cinnamon', 'Almond'}",Tawny,20.0,Douro,{'nan'},NaN
486,33.320000,Touriga Franca,Natural Cork,Portugal,"{'Caramel', 'Jammy', 'Fig'}",Tawny,20.0,Douro,{'nan'},NaN
708,39.986667,Touriga Nacional,Natural Cork,Portugal,"{'Walnut', 'Red Plum', 'Raisin', 'Fig', 'Toffe...",Tawny,20.0,Douro,{'nan'},NaN
1243,39.986667,Touriga Nacional,Natural Cork,Portugal,"{'Cedar', 'Fig', 'Black Plum', 'Leather'}",Tawny,20.0,Douro,{'nan'},NaN

## Visuals

In [203]:
df.columns

Index(['Price', 'Grape', 'Closure', 'Country', 'Characteristics', 'Type',
       'ABV', 'Region', 'Style', 'Vintage'],
      dtype='str')

In [212]:
df = df[['Grape', 'Type', 'Region', 'Style']]

In [218]:
class WinePattern(psp.bip.CartesianPattern):
    DimensionTypes = {
        'Grape': GrapePattern,
        # 'Country': CountryPattern,
        'Type': TypePattern,
        # 'ABV': ABVPattern,
        'Region': RegionPattern,
        'Style': StylePattern,
    }

In [219]:
for f in df.columns:
    if df[f].isna().any():
        p = WinePattern.DimensionTypes[f].get_min_pattern()
        df[f] = df[f].fillna(p)
        print(f"Found NaN values in dimension {f}. Replace them by pattern: {p}")

In [220]:
ps = psp.PatternStructure(WinePattern)
ps.fit(df.to_dict('index'), min_atom_support=0.1, use_tqdm=True)
print('#objects x #atomic_patterns', ps.shape)

Compute atomic extents:   0%|          | 0/539 [00:00<?, ?it/s]

Compute atomic extents:   6%|▌         | 32/539 [00:00<00:01, 283.59it/s]

Compute atomic extents:  13%|█▎        | 68/539 [00:00<00:01, 319.98it/s]

Compute atomic extents:  19%|█▊        | 101/539 [00:00<00:01, 322.88it/s]

Compute atomic extents:  25%|██▍       | 134/539 [00:00<00:01, 313.52it/s]

Iter premise candidates: 6342019it [6:10:16, 285.47it/s]00:01, 313.52it/s]
Iterate subgroup candidates: 2.29Mit [1:18:04, 490it/s]


Compute atomic extents:  28%|██▊       | 149/539 [00:37<03:15,  1.99it/s]

Compute atomic extents:  33%|███▎      | 178/539 [00:37<01:56,  3.09it/s]

Compute atomic extents:  39%|███▉      | 209/539 [00:37<01:09,  4.75it/s]

Compute atomic extents:  44%|████▍     | 238/539 [00:37<00:43,  6.94it/s]

Compute atomic extents:  50%|█████     | 270/539 [00:37<00:26, 10.33it/s]

Compute atomic extents:  56%|█████▌    | 302/539 [00:38<00:15, 15.04it/s]

Compute atomic extents:  62%|██████▏   | 332/539 [00:38<00:09, 20.86it/s]

Compute atomic extents:  67%|██████▋   | 359/539 [00:38<00:06, 27.89it/s]

Compute atomic extents:  71%|███████   | 384/539 [00:38<00:04, 36.23it/s]

Compute atomic extents:  76%|███████▌  | 407/539 [00:38<00:02, 45.27it/s]

Compute atomic extents:  79%|███████▉  | 428/539 [00:38<00:01, 56.03it/s]

Compute atomic extents:  83%|████████▎ | 448/539 [00:38<00:01, 68.75it/s]

Compute atomic extents:  89%|████████▉ | 481/539 [00:38<00:00, 96.31it/s]

Compute atomic extents: 100%|██████████| 539/539 [00:39<00:00, 13.76it/s]
Compute order of patterns: 100%|██████████| 224/224 [00:00<00:00, 49184.59it/s]

#objects x #atomic_patterns (1284, 224)

In [221]:
concepts = ps.mine_concepts(min_delta_stability=30, min_support=500, algorithm='gSofia', use_tqdm=True)
len(concepts)

gSofia algorithm: 100%|█████████▉| 223/224 [00:00<00:00, 1318.54it/s]
Compute intents: 100%|██████████| 236/236 [00:00<00:00, 655.86it/s]

236

In [224]:
patterns = [
    WinePattern.get_min_pattern(),
]

for extent, intent in concepts[:10]:
    patterns.extend([
        WinePattern(intent),
    ])

len(patterns)

11

In [225]:
node_labels = [str(p)+'<br>'+f"support: {ps.measure_support(p):.0f}" for p in patterns]
direct_subpatterns = [{patterns.index(q) for q in patterns if q > p and not any(q > r > p for r in patterns)} for p in patterns]

print(csp.io.to_mermaid_diagram(node_labels, direct_subpatterns))

flowchart TD
A["{}<br>support: 1284"];
B["{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Shiraz', 'Grenache', 'Chardonnay', 'Malbec'}, 'Type': {'White', 'Red', 'Rosé'}}<br>support: 803"];
C["{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Grenache', 'Chardonnay', 'Shiraz'}, 'Type': {'White', 'Red', 'Rosé'}}<br>support: 766"];
D["{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Grenache', 'Chardonnay', 'Malbec'}, 'Type': {'White', 'Red', 'Rosé'}}<br>support: 760"];
E["{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Pinot Noir', 'Grenache', 'Chardonnay', 'Malbec', 'Shiraz'}, 'Type': {'White', 'Red', 'Rosé'}}<br>support: 759"];
F["{'Grape': {'Sauvignon Blanc', 'Merlot', 'Cabernet Sauvignon', 'Pinot Noir', 'Grenache', 'Chardonnay', 'Malbec', 'Shiraz'}, 'Type': {'White', 'Red', 'Rosé'}}<br>support: 747"];
G["{'Grape': {'Sauvignon Blanc', 'Chardonnay', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Grenache'}, 'Type': {'White', 'Red', 'Rosé'}}<br>support: 723"];
H["{'Grape': {'Sauvignon Blanc', 'Chardonnay', 'Shiraz', 'Tempranillo', 'Cabernet Sauvignon', 'Pinot Noir', 'Grenache'}, 'Type': {'White', 'Red', 'Rosé'}}<br>support: 722"];
I["{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Shiraz', 'Grenache', 'Chardonnay', 'Malbec'}, 'Type': {'White', 'Red'}}<br>support: 722"];
J["{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Chardonnay', 'Malbec', 'Shiraz'}, 'Type': {'White', 'Red', 'Rosé'}}<br>support: 721"];
K["{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Merlot', 'Pinot Noir', 'Grenache', 'Chardonnay', 'Malbec', 'Shiraz'}, 'Type': {'White', 'Red', 'Rosé'}}<br>support: 716"];

A --- B;
B --- C;
B --- D;
B --- E;
B --- F;
B --- I;
B --- J;
B --- K;
C --- G;
C --- H;
D --- G;
E --- H;

In [226]:
euler_df = dict()
for p in patterns:
  extent = ps.extent(p)
  euler_df[str(p)] = [g in extent for g in ps.objects]

euler_df = pd.DataFrame(euler_df)
euler_df

,{},"{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Shiraz', 'Grenache', 'Chardonnay', 'Malbec'}, 'Type': {'White', 'Red', 'Rosé'}}","{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Grenache', 'Chardonnay', 'Shiraz'}, 'Type': {'White', 'Red', 'Rosé'}}","{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Grenache', 'Chardonnay', 'Malbec'}, 'Type': {'White', 'Red', 'Rosé'}}","{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Pinot Noir', 'Grenache', 'Chardonnay', 'Malbec', 'Shiraz'}, 'Type': {'White', 'Red', 'Rosé'}}","{'Grape': {'Sauvignon Blanc', 'Merlot', 'Cabernet Sauvignon', 'Pinot Noir', 'Grenache', 'Chardonnay', 'Malbec', 'Shiraz'}, 'Type': {'White', 'Red', 'Rosé'}}","{'Grape': {'Sauvignon Blanc', 'Chardonnay', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Grenache'}, 'Type': {'White', 'Red', 'Rosé'}}","{'Grape': {'Sauvignon Blanc', 'Chardonnay', 'Shiraz', 'Tempranillo', 'Cabernet Sauvignon', 'Pinot Noir', 'Grenache'}, 'Type': {'White', 'Red', 'Rosé'}}","{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Shiraz', 'Grenache', 'Chardonnay', 'Malbec'}, 'Type': {'White', 'Red'}}","{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Chardonnay', 'Malbec', 'Shiraz'}, 'Type': {'White', 'Red', 'Rosé'}}","{'Grape': {'Sauvignon Blanc', 'Tempranillo', 'Merlot', 'Pinot Noir', 'Grenache', 'Chardonnay', 'Malbec', 'Shiraz'}, 'Type': {'White', 'Red', 'Rosé'}}"
0,True,True,True,True,True,False,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
1279,True,False,False,False,False,False,False,False,False,False,False
1280,True,True,True,True,True,True,True,True,False,True,True
1281,True,True,True,True,True,True,True,True,True,True,False
1282,True,True,True,True,True,True,True,True,True,True,False
1283,True,False,False,False,False,False,False,False,False,False,False

In [227]:
euler_df.astype(int).to_csv('euler_df.csv')